# Get list of entrants

In [98]:
tournament_slug = 'ngpr'
tournament_slug = 'aav'
event_name = 'Melee Redemption'
event_name = 'Melee Singles'

In [99]:
import json
from gql import gql, Client
from gql.transport.requests import RequestsHTTPTransport

In [100]:
%%bash
source ~/.bashrc

In [101]:
import os

auth_token = os.environ['SMASHGG_TOKEN']
api_version = 'alpha'

In [102]:
transport = RequestsHTTPTransport(
    url=f'https://api.start.gg/gql/{api_version}',
    headers={'Authorization': f'Bearer {auth_token}'},
    use_json=True,
)

client = Client(transport=transport, fetch_schema_from_transport=False)

In [103]:
# Define the API endpoint and query for tournament details
query = gql("""
query TournamentQuery($slug: String!) {
    tournament(slug: $slug) {
        id
        name
        city
        state
        countryCode
        startAt
        endAt
        events {
            id
            name
            numEntrants
        }
    }
}
""")

variables = {"slug": tournament_slug}

# Execute the query
try:
        tournament_result = client.execute(query, variable_values=variables)
        print(json.dumps(tournament_result, indent=2))
except Exception as e:
        print("Error fetching tournament details:", e)

{
  "tournament": {
    "id": 804685,
    "name": "Allston Allstars V - Tom's Birthday Bash!",
    "city": "Boston",
    "state": 1,
    "countryCode": "US",
    "startAt": 1754157600,
    "endAt": 1754190000,
    "events": [
      {
        "id": 1410041,
        "name": "Melee Singles",
        "numEntrants": 96
      },
      {
        "id": 1410043,
        "name": "Project+ Singles",
        "numEntrants": 20
      },
      {
        "id": 1410221,
        "name": "Melee Crews (5v5)",
        "numEntrants": 14
      },
      {
        "id": 1410048,
        "name": "Project+ Doubles",
        "numEntrants": 2
      },
      {
        "id": 1410042,
        "name": "Melee Redemption",
        "numEntrants": 0
      }
    ]
  }
}

In [104]:
# Extract the event id for "Melee Singles"
events = tournament_result['tournament']['events']
melee_singles_id = next((event['id'] for event in events if event_name in event['name']), None)
print(f"{event_name} Event ID: {melee_singles_id}")

Melee Singles Event ID: 1410041

In [105]:
# Query to get entrants for Melee Singles
entrants_query = gql("""
query EventEntrants($eventId: ID!) {
    event(id: $eventId) {
        entrants(query: {page: 1, perPage: 512}) {
            nodes {
                id
                name
                participants {
                    gamerTag
                }
            }
        }
    }
}
""")

entrants_variables = {"eventId": melee_singles_id}

try:
        entrants_result = client.execute(entrants_query, variable_values=entrants_variables)
        print(json.dumps(entrants_result, indent=2))
except Exception as e:
        print("Error fetching entrants:", e)

{
  "event": {
    "entrants": {
      "nodes": [
        {
          "id": 20855091,
          "name": "Sabriel",
          "participants": [
            {
              "gamerTag": "Sabriel"
            }
          ]
        },
        {
          "id": 20854858,
          "name": "sfy | LordTet",
          "participants": [
            {
              "gamerTag": "LordTet"
            }
          ]
        },
        {
          "id": 20852388,
          "name": "BU | BBron",
          "participants": [
            {
              "gamerTag": "BBron"
            }
          ]
        },
        {
          "id": 20852276,
          "name": "DarkCloud",
          "participants": [
            {
              "gamerTag": "DarkCloud"
            }
          ]
        },
        {
          "id": 20852205,
          "name": "MattDotZeb",
          "participants": [
            {
              "gamerTag": "MattDotZeb"
            }
          ]
        },
        {
          "id": 20851915,
          "name": "Wishy",
          "participants": [
            {
              "gamerTag": "Wishy"
            }
          ]
        },
        {
          "id": 20842180,
          "name": "Nico",
          "participants": [
            {
              "gamerTag": "Nico"
            }
          ]
        },
        {
          "id": 20842018,
          "name": "Wolf",
          "participants": [
            {
              "gamerTag": "Wolf"
            }
          ]
        },
        {
          "id": 20838313,
          "name": "PRIONBOIL",
          "participants": [
            {
              "gamerTag": "PRIONBOIL"
            }
          ]
        },
        {
          "id": 20826451,
          "name": "Blueish | Chanterelle",
          "participants": [
            {
              "gamerTag": "Chanterelle"
            }
          ]
        },
        {
          "id": 20825653,
          "name": "ICSP | s1matic",
          "participants": [
            {
              "gamerTag": "s1matic"
            }
          ]
        },
        {
          "id": 20825651,
          "name": "AFMCX | Lermonz",
          "participants": [
            {
              "gamerTag": "Lermonz"
            }
          ]
        },
        {
          "id": 20825608,
          "name": "SIX | Embry",
          "participants": [
            {
              "gamerTag": "Embry"
            }
          ]
        },
        {
          "id": 20825426,
          "name": "kaimen",
          "participants": [
            {
              "gamerTag": "kaimen"
            }
          ]
        },
        {
          "id": 20825257,
          "name": "RedbulSuprnova | P\u00e9piNoCreme",
          "participants": [
            {
              "gamerTag": "P\u00e9piNoCreme"
            }
          ]
        },
        {
          "id": 20824917,
          "name": "c0 | Monochrome",
          "participants": [
            {
              "gamerTag": "Monochrome"
            }
          ]
        },
        {
          "id": 20819954,
          "name": "Cranberry",
          "participants": [
            {
              "gamerTag": "Cranberry"
            }
          ]
        },
        {
          "id": 20814931,
          "name": "zip zip",
          "participants": [
            {
              "gamerTag": "zip zip"
            }
          ]
        },
        {
          "id": 20809261,
          "name": "Downey",
          "participants": [
            {
              "gamerTag": "Downey"
            }
          ]
        },
        {
          "id": 20803764,
          "name": "Dominion",
          "participants": [
            {
              "gamerTag": "Dominion"
            }
          ]
        },
        {
          "id": 20802361,
          "name": "brennan",
          "participants": [
            {
              "gamerTag": "brennan"
            }
          ]
        },
        {
          "id": 20801241,
          "name": "nikhil",
          "participants": [
            {
              "gamerTag": "nikhil"
            }
          ]
        },
        {
          "id": 20799153,
          "name": "lioX0X0",
          "participants": [
            {
              "gamerTag": "lioX0X0"
            }
          ]
        },
        {
          "id": 20799130,
          "name": "Sleeper",
          "participants": [
            {
              "gamerTag": "Sleeper"
            }
          ]
        },
        {
          "id": 20799010,
          "name": "Rarik",
          "participants": [
            {
              "gamerTag": "Rarik"
            }
          ]
        },
        {
          "id": 20798985,
          "name": "Yifu",
          "participants": [
            {
              "gamerTag": "Yifu"
            }
          ]
        },
        {
          "id": 20798969,
          "name": "Sweat",
          "participants": [
            {
              "gamerTag": "Sweat"
            }
          ]
        },
        {
          "id": 20798957,
          "name": "Rekzuh",
          "participants": [
            {
              "gamerTag": "Rekzuh"
            }
          ]
        },
        {
          "id": 20798950,
          "name": "Chimp's Friend | Saltzy",
          "participants": [
            {
              "gamerTag": "Saltzy"
            }
          ]
        },
        {
          "id": 20794076,
          "name": "eveningstar",
          "participants": [
            {
              "gamerTag": "eveningstar"
            }
          ]
        },
        {
          "id": 20793586,
          "name": "Qwerty",
          "participants": [
            {
              "gamerTag": "Qwerty"
            }
          ]
        },
        {
          "id": 20792263,
          "name": "Roughnut29",
          "participants": [
            {
              "gamerTag": "Roughnut29"
            }
          ]
        },
        {
          "id": 20763728,
          "name": "YWRM | Q",
          "participants": [
            {
              "gamerTag": "Q"
            }
          ]
        },
        {
          "id": 20698945,
          "name": "DrEsportstTeam | EduPorp",
          "participants": [
            {
              "gamerTag": "EduPorp"
            }
          ]
        },
        {
          "id": 20605019,
          "name": "Nage",
          "participants": [
            {
              "gamerTag": "Nage"
            }
          ]
        },
        {
          "id": 20603036,
          "name": "N0va | WAS | N0va",
          "participants": [
            {
              "gamerTag": "N0va"
            }
          ]
        },
        {
          "id": 20602379,
          "name": "$G|MP | Bank",
          "participants": [
            {
              "gamerTag": "Bank"
            }
          ]
        },
        {
          "id": 20600643,
          "name": "M.SKITTLE",
          "participants": [
            {
              "gamerTag": "M.SKITTLE"
            }
          ]
        },
        {
          "id": 20599180,
          "name": "UML | Blip Blip You Dip",
          "participants": [
            {
              "gamerTag": "Blip Blip You Dip"
            }
          ]
        },
        {
          "id": 20597338,
          "name": "N0va | Breathlessx22",
          "participants": [
            {
              "gamerTag": "Breathlessx22"
            }
          ]
        },
        {
          "id": 20596638,
          "name": "coinstar",
          "participants": [
            {
              "gamerTag": "coinstar"
            }
          ]
        },
        {
          "id": 20596511,
          "name": "Coffee",
          "participants": [
            {
              "gamerTag": "Coffee"
            }
          ]
        },
        {
          "id": 20595805,
          "name": "bfu",
          "participants": [
            {
              "gamerTag": "bfu"
            }
          ]
        },
        {
          "id": 20595089,
          "name": "Q",
          "participants": [
            {
              "gamerTag": "Q"
            }
          ]
        },
        {
          "id": 20592362,
          "name": "kzgrobb",
          "participants": [
            {
              "gamerTag": "kzgrobb"
            }
          ]
        },
        {
          "id": 20591181,
          "name": "GioIzHawt",
          "participants": [
            {
              "gamerTag": "GioIzHawt"
            }
          ]
        },
        {
          "id": 20588253,
          "name": "Duhaime",
          "participants": [
            {
              "gamerTag": "Duhaime"
            }
          ]
        },
        {
          "id": 20587511,
          "name": "Groggy",
          "participants": [
            {
              "gamerTag": "Groggy"
            }
          ]
        },
        {
          "id": 20587379,
          "name": "Raf",
          "participants": [
            {
              "gamerTag": "Raf"
            }
          ]
        },
        {
          "id": 20587334,
          "name": "Essence",
          "participants": [
            {
              "gamerTag": "Essence"
            }
          ]
        },
        {
          "id": 20586596,
          "name": "Desmond",
          "participants": [
            {
              "gamerTag": "Desmond"
            }
          ]
        },
        {
          "id": 20585659,
          "name": "hc | Jeep God",
          "participants": [
            {
              "gamerTag": "Jeep God"
            }
          ]
        },
        {
          "id": 20585655,
          "name": "hc | keke",
          "participants": [
            {
              "gamerTag": "keke"
            }
          ]
        },
        {
          "id": 20585636,
          "name": "hc | saucymain",
          "participants": [
            {
              "gamerTag": "saucymain"
            }
          ]
        },
        {
          "id": 20583937,
          "name": "NEU | cybert",
          "participants": [
            {
              "gamerTag": "cybert"
            }
          ]
        },
        {
          "id": 20583833,
          "name": "wub",
          "participants": [
            {
              "gamerTag": "wub"
            }
          ]
        },
        {
          "id": 20583615,
          "name": "Tichinde925",
          "participants": [
            {
              "gamerTag": "Tichinde925"
            }
          ]
        },
        {
          "id": 20583582,
          "name": "bleop",
          "participants": [
            {
              "gamerTag": "bleop"
            }
          ]
        },
        {
          "id": 20583462,
          "name": "hc | Newquake",
          "participants": [
            {
              "gamerTag": "Newquake"
            }
          ]
        },
        {
          "id": 20583420,
          "name": "stir fried",
          "participants": [
            {
              "gamerTag": "stir fried"
            }
          ]
        },
        {
          "id": 20583229,
          "name": "hc | chery*",
          "participants": [
            {
              "gamerTag": "chery*"
            }
          ]
        },
        {
          "id": 20583175,
          "name": "zaubermaus",
          "participants": [
            {
              "gamerTag": "zaubermaus"
            }
          ]
        },
        {
          "id": 20582996,
          "name": "hc | pluto",
          "participants": [
            {
              "gamerTag": "pluto"
            }
          ]
        },
        {
          "id": 20582798,
          "name": "cynics",
          "participants": [
            {
              "gamerTag": "cynics"
            }
          ]
        },
        {
          "id": 20582678,
          "name": "TeaKay",
          "participants": [
            {
              "gamerTag": "TeaKay"
            }
          ]
        },
        {
          "id": 20582608,
          "name": "Kumatora",
          "participants": [
            {
              "gamerTag": "Kumatora"
            }
          ]
        },
        {
          "id": 20582543,
          "name": "Ant",
          "participants": [
            {
              "gamerTag": "Ant"
            }
          ]
        },
        {
          "id": 20581997,
          "name": "Tommy",
          "participants": [
            {
              "gamerTag": "Tommy"
            }
          ]
        },
        {
          "id": 20581475,
          "name": "oliver",
          "participants": [
            {
              "gamerTag": "oliver"
            }
          ]
        },
        {
          "id": 20581466,
          "name": "supremelol",
          "participants": [
            {
              "gamerTag": "supremelol"
            }
          ]
        },
        {
          "id": 20580944,
          "name": "Rose | Blue Velvet",
          "participants": [
            {
              "gamerTag": "Blue Velvet"
            }
          ]
        },
        {
          "id": 20580892,
          "name": "hc | Babs",
          "participants": [
            {
              "gamerTag": "Babs"
            }
          ]
        },
        {
          "id": 20580861,
          "name": "oz",
          "participants": [
            {
              "gamerTag": "oz"
            }
          ]
        },
        {
          "id": 20580613,
          "name": "Andrew",
          "participants": [
            {
              "gamerTag": "Andrew"
            }
          ]
        },
        {
          "id": 20580575,
          "name": "Juicebox",
          "participants": [
            {
              "gamerTag": "Juicebox"
            }
          ]
        },
        {
          "id": 20580547,
          "name": "Exarch",
          "participants": [
            {
              "gamerTag": "Exarch"
            }
          ]
        },
        {
          "id": 20580544,
          "name": "Vexoskeleton",
          "participants": [
            {
              "gamerTag": "Vexoskeleton"
            }
          ]
        },
        {
          "id": 20580338,
          "name": "MOOP",
          "participants": [
            {
              "gamerTag": "MOOP"
            }
          ]
        },
        {
          "id": 20573810,
          "name": "DadsAkimbo",
          "participants": [
            {
              "gamerTag": "DadsAkimbo"
            }
          ]
        },
        {
          "id": 20573757,
          "name": "Comcast | The CoveCare Scare",
          "participants": [
            {
              "gamerTag": "The CoveCare Scare"
            }
          ]
        },
        {
          "id": 20572722,
          "name": "Shuffle",
          "participants": [
            {
              "gamerTag": "Shuffle"
            }
          ]
        },
        {
          "id": 20568692,
          "name": "heeg | meep",
          "participants": [
            {
              "gamerTag": "meep"
            }
          ]
        },
        {
          "id": 20568506,
          "name": "Team Porp | Dr. Lame",
          "participants": [
            {
              "gamerTag": "Dr. Lame"
            }
          ]
        },
        {
          "id": 20568131,
          "name": "HoG | Lati",
          "participants": [
            {
              "gamerTag": "Lati"
            }
          ]
        },
        {
          "id": 20567819,
          "name": "Project",
          "participants": [
            {
              "gamerTag": "Project"
            }
          ]
        },
        {
          "id": 20567446,
          "name": "N0va | hc | Coolslice",
          "participants": [
            {
              "gamerTag": "Coolslice"
            }
          ]
        },
        {
          "id": 20565359,
          "name": "Karils | Conflict",
          "participants": [
            {
              "gamerTag": "Conflict"
            }
          ]
        },
        {
          "id": 20564883,
          "name": "Hyouka | Nairial",
          "participants": [
            {
              "gamerTag": "Nairial"
            }
          ]
        },
        {
          "id": 20564827,
          "name": "HoG | Arty",
          "participants": [
            {
              "gamerTag": "Arty"
            }
          ]
        },
        {
          "id": 20564582,
          "name": "Future Shock",
          "participants": [
            {
              "gamerTag": "Future Shock"
            }
          ]
        },
        {
          "id": 20564530,
          "name": "Greenstach",
          "participants": [
            {
              "gamerTag": "Greenstach"
            }
          ]
        },
        {
          "id": 20564510,
          "name": "Ember",
          "participants": [
            {
              "gamerTag": "Ember"
            }
          ]
        },
        {
          "id": 20564432,
          "name": "Golden",
          "participants": [
            {
              "gamerTag": "Golden"
            }
          ]
        },
        {
          "id": 20564369,
          "name": "bonfire10",
          "participants": [
            {
              "gamerTag": "bonfire10"
            }
          ]
        },
        {
          "id": 20564347,
          "name": "glock in my toyota",
          "participants": [
            {
              "gamerTag": "glock in my toyota"
            }
          ]
        },
        {
          "id": 20564252,
          "name": "MATE | Kalvar",
          "participants": [
            {
              "gamerTag": "Kalvar"
            }
          ]
        }
      ]
    }
  }
}

In [106]:
import polars as pl

# Extract entrant data and flatten participants' gamerTags

entrant_nodes = entrants_result['event']['entrants']['nodes']
data = []
for entrant in entrant_nodes:
    entrant_id = entrant['id']
    entrant_name = entrant['name']
    # There may be multiple participants per entrant; join their gamerTags with comma
    gamer_tags = [p['gamerTag'] for p in entrant.get('participants', [])]
    gamer_tag = ', '.join(gamer_tags)
    data.append({'id': entrant_id, 'name': entrant_name, 'gamertag': gamer_tag})

entrants = pl.DataFrame(data)
entrants

shape: (96, 3)
┌──────────┬──────────────────────────────┬────────────────────┐
│ id       ┆ name                         ┆ gamertag           │
│ ---      ┆ ---                          ┆ ---                │
│ i64      ┆ str                          ┆ str                │
╞══════════╪══════════════════════════════╪════════════════════╡
│ 20855091 ┆ Sabriel                      ┆ Sabriel            │
│ 20854858 ┆ sfy | LordTet                ┆ LordTet            │
│ 20852388 ┆ BU | BBron                   ┆ BBron              │
│ 20852276 ┆ DarkCloud                    ┆ DarkCloud          │
│ 20852205 ┆ MattDotZeb                   ┆ MattDotZeb         │
│ 20851915 ┆ Wishy                        ┆ Wishy              │
│ 20842180 ┆ Nico                         ┆ Nico               │
│ 20842018 ┆ Wolf                         ┆ Wolf               │
│ 20838313 ┆ PRIONBOIL                    ┆ PRIONBOIL          │
│ 20826451 ┆ Blueish | Chanterelle        ┆ Chanterelle        │
│ 20825653 ┆ ICSP | s1matic               ┆ s1matic            │
│ 20825651 ┆ AFMCX | Lermonz              ┆ Lermonz            │
│ 20825608 ┆ SIX | Embry                  ┆ Embry              │
│ 20825426 ┆ kaimen                       ┆ kaimen             │
│ 20825257 ┆ RedbulSuprnova | PépiNoCreme ┆ PépiNoCreme        │
│ 20824917 ┆ c0 | Monochrome              ┆ Monochrome         │
│ 20819954 ┆ Cranberry                    ┆ Cranberry          │
│ 20814931 ┆ zip zip                      ┆ zip zip            │
│ 20809261 ┆ Downey                       ┆ Downey             │
│ 20803764 ┆ Dominion                     ┆ Dominion           │
│ 20802361 ┆ brennan                      ┆ brennan            │
│ 20801241 ┆ nikhil                       ┆ nikhil             │
│ 20799153 ┆ lioX0X0                      ┆ lioX0X0            │
│ 20799130 ┆ Sleeper                      ┆ Sleeper            │
│ 20799010 ┆ Rarik                        ┆ Rarik              │
│ 20798985 ┆ Yifu                         ┆ Yifu               │
│ 20798969 ┆ Sweat                        ┆ Sweat              │
│ 20798957 ┆ Rekzuh                       ┆ Rekzuh             │
│ 20798950 ┆ Chimp's Friend | Saltzy      ┆ Saltzy             │
│ 20794076 ┆ eveningstar                  ┆ eveningstar        │
│ 20793586 ┆ Qwerty                       ┆ Qwerty             │
│ 20792263 ┆ Roughnut29                   ┆ Roughnut29         │
│ 20763728 ┆ YWRM | Q                     ┆ Q                  │
│ 20698945 ┆ DrEsportstTeam | EduPorp     ┆ EduPorp            │
│ 20605019 ┆ Nage                         ┆ Nage               │
│ 20603036 ┆ N0va | WAS | N0va            ┆ N0va               │
│ 20602379 ┆ $G|MP | Bank                 ┆ Bank               │
│ 20600643 ┆ M.SKITTLE                    ┆ M.SKITTLE          │
│ 20599180 ┆ UML | Blip Blip You Dip      ┆ Blip Blip You Dip  │
│ 20597338 ┆ N0va | Breathlessx22         ┆ Breathlessx22      │
│ 20596638 ┆ coinstar                     ┆ coinstar           │
│ 20596511 ┆ Coffee                       ┆ Coffee             │
│ 20595805 ┆ bfu                          ┆ bfu                │
│ 20595089 ┆ Q                            ┆ Q                  │
│ 20592362 ┆ kzgrobb                      ┆ kzgrobb            │
│ 20591181 ┆ GioIzHawt                    ┆ GioIzHawt          │
│ 20588253 ┆ Duhaime                      ┆ Duhaime            │
│ 20587511 ┆ Groggy                       ┆ Groggy             │
│ 20587379 ┆ Raf                          ┆ Raf                │
│ 20587334 ┆ Essence                      ┆ Essence            │
│ 20586596 ┆ Desmond                      ┆ Desmond            │
│ 20585659 ┆ hc | Jeep God                ┆ Jeep God           │
│ 20585655 ┆ hc | keke                    ┆ keke               │
│ 20585636 ┆ hc | saucymain               ┆ saucymain          │
│ 20583937 ┆ NEU | cybert                 ┆ cybert             │
│ 20583833 ┆ wub                          ┆ wub                │
│ 20583615 ┆ Tichinde925                  ┆ Tichinde925        │
│ 20583582 ┆ bleop                        ┆ bleop              │
│ 20583462 ┆ hc | Newquake                ┆ Newquake           │
│ 20583420 ┆ stir fried                   ┆ stir fried         │
│ 20583229 ┆ hc | chery*                  ┆ chery*             │
│ 20583175 ┆ zaubermaus                   ┆ zaubermaus         │
│ 20582996 ┆ hc | pluto                   ┆ pluto              │
│ 20582798 ┆ cynics                       ┆ cynics             │
│ 20582678 ┆ TeaKay                       ┆ TeaKay             │
│ 20582608 ┆ Kumatora                     ┆ Kumatora           │
│ 20582543 ┆ Ant                          ┆ Ant                │
│ 20581997 ┆ Tommy                        ┆ Tommy              │
│ 20581475 ┆ oliver                       ┆ oliver             │
│ 20581466 ┆ supremelol                   ┆ supremelol         │
│ 20580944 ┆ Rose | Blue Velvet           ┆ Blue Velvet        │
│ 20580892 ┆ hc | Babs                    ┆ Babs               │
│ 20580861 ┆ oz                           ┆ oz                 │
│ 20580613 ┆ Andrew                       ┆ Andrew             │
│ 20580575 ┆ Juicebox                     ┆ Juicebox           │
│ 20580547 ┆ Exarch                       ┆ Exarch             │
│ 20580544 ┆ Vexoskeleton                 ┆ Vexoskeleton       │
│ 20580338 ┆ MOOP                         ┆ MOOP               │
│ 20573810 ┆ DadsAkimbo                   ┆ DadsAkimbo         │
│ 20573757 ┆ Comcast | The CoveCare Scare ┆ The CoveCare Scare │
│ 20572722 ┆ Shuffle                      ┆ Shuffle            │
│ 20568692 ┆ heeg | meep                  ┆ meep               │
│ 20568506 ┆ Team Porp | Dr. Lame         ┆ Dr. Lame           │
│ 20568131 ┆ HoG | Lati                   ┆ Lati               │
│ 20567819 ┆ Project                      ┆ Project            │
│ 20567446 ┆ N0va | hc | Coolslice        ┆ Coolslice          │
│ 20565359 ┆ Karils | Conflict            ┆ Conflict           │
│ 20564883 ┆ Hyouka | Nairial             ┆ Nairial            │
│ 20564827 ┆ HoG | Arty                   ┆ Arty               │
│ 20564582 ┆ Future Shock                 ┆ Future Shock       │
│ 20564530 ┆ Greenstach                   ┆ Greenstach         │
│ 20564510 ┆ Ember                        ┆ Ember              │
│ 20564432 ┆ Golden                       ┆ Golden             │
│ 20564369 ┆ bonfire10                    ┆ bonfire10          │
│ 20564347 ┆ glock in my toyota           ┆ glock in my toyota │
│ 20564252 ┆ MATE | Kalvar                ┆ Kalvar             │
└──────────┴──────────────────────────────┴────────────────────┘

In [107]:
entrant_gamertags = entrants.select(pl.col('gamertag').str.to_lowercase()).to_series().to_list()

# collect seeding

In [108]:
player_ratings = pl.read_parquet('data/player-ratings.parquet')

In [ ]:
pl.Config(tbl_rows=100)
entrant_ratings = (
    entrants
    .with_columns(pl.col('gamertag').str.to_lowercase())
    .join(
        player_ratings
            .with_columns(pl.col('tag').str.split(' | ').list.last().str.to_lowercase()),
        how='full',
        left_on='gamertag',
        right_on='tag',
    )
    #.filter(
    #    (pl.col('tag').str.to_lowercase() == pl.col('gamertag').str.to_lowercase()) |
    #    pl.col('gamertag').is_null()
    #)
    .filter(pl.col('gamertag').is_not_null())
    .sort('rating', descending=True)
    .group_by('id').first()
    .fill_null(0)
    .sort('rating', descending=True)
)
display(entrant_ratings)

shape: (96, 6)
┌──────────┬───────────────────┬───────────────┬───────────────────┬───────────┬───────────────────┐
│ id       ┆ name              ┆ gamertag      ┆ url               ┆ rating    ┆ tag               │
│ ---      ┆ ---               ┆ ---           ┆ ---               ┆ ---       ┆ ---               │
│ i64      ┆ str               ┆ str           ┆ str               ┆ f64       ┆ str               │
╞══════════╪═══════════════════╪═══════════════╪═══════════════════╪═══════════╪═══════════════════╡
│ 20564252 ┆ MATE | Kalvar     ┆ kalvar        ┆ /league/nemelee/p ┆ 43.762813 ┆ kalvar            │
│          ┆                   ┆               ┆ layer/C206957…    ┆           ┆                   │
│ 20564369 ┆ bonfire10         ┆ bonfire10     ┆ /league/nemelee/p ┆ 42.003164 ┆ bonfire10         │
│          ┆                   ┆               ┆ layer/C9B8492…    ┆           ┆                   │
│ 20564347 ┆ glock in my       ┆ glock in my   ┆ /league/nemelee/p ┆ 39.884903 ┆ glock in my       │
│          ┆ toyota            ┆ toyota        ┆ layer/1FE504A…    ┆           ┆ toyota            │
│ 20567819 ┆ Project           ┆ project       ┆ /league/nemelee/p ┆ 39.53775  ┆ project           │
│          ┆                   ┆               ┆ layer/55203EA…    ┆           ┆                   │
│ 20564510 ┆ Ember             ┆ ember         ┆ /league/nemelee/p ┆ 39.526006 ┆ ember             │
│          ┆                   ┆               ┆ layer/10F6134…    ┆           ┆                   │
│ 20595089 ┆ Q                 ┆ q             ┆ /league/nemelee/p ┆ 39.371221 ┆ q                 │
│          ┆                   ┆               ┆ layer/5C19CFD…    ┆           ┆                   │
│ 20763728 ┆ YWRM | Q          ┆ q             ┆ /league/nemelee/p ┆ 39.371221 ┆ q                 │
│          ┆                   ┆               ┆ layer/5C19CFD…    ┆           ┆                   │
│ 20564883 ┆ Hyouka | Nairial  ┆ nairial       ┆ /league/nemelee/p ┆ 38.907933 ┆ nairial           │
│          ┆                   ┆               ┆ layer/39180F6…    ┆           ┆                   │
│ 20602379 ┆ $G|MP | Bank      ┆ bank          ┆ /league/nemelee/p ┆ 38.823131 ┆ bank              │
│          ┆                   ┆               ┆ layer/E85EE0F…    ┆           ┆                   │
│ 20564827 ┆ HoG | Arty        ┆ arty          ┆ /league/nemelee/p ┆ 38.74196  ┆ arty              │
│          ┆                   ┆               ┆ layer/CEBCAD4…    ┆           ┆                   │
│ 20596511 ┆ Coffee            ┆ coffee        ┆ /league/nemelee/p ┆ 38.699126 ┆ coffee            │
│          ┆                   ┆               ┆ layer/25479C6…    ┆           ┆                   │
│ 20581997 ┆ Tommy             ┆ tommy         ┆ /league/nemelee/p ┆ 38.407676 ┆ tommy             │
│          ┆                   ┆               ┆ layer/3530B49…    ┆           ┆                   │
│ 20794076 ┆ eveningstar       ┆ eveningstar   ┆ /league/nemelee/p ┆ 38.216794 ┆ eveningstar       │
│          ┆                   ┆               ┆ layer/F3FCF46…    ┆           ┆                   │
│ 20564432 ┆ Golden            ┆ golden        ┆ /league/nemelee/p ┆ 38.103436 ┆ golden            │
│          ┆                   ┆               ┆ layer/CC999B8…    ┆           ┆                   │
│ 20698945 ┆ DrEsportstTeam |  ┆ eduporp       ┆ /league/nemelee/p ┆ 37.224269 ┆ eduporp           │
│          ┆ EduPorp           ┆               ┆ layer/FB122D4…    ┆           ┆                   │
│ 20568692 ┆ heeg | meep       ┆ meep          ┆ /league/nemelee/p ┆ 36.874359 ┆ meep              │
│          ┆                   ┆               ┆ layer/0C1E5B6…    ┆           ┆                   │
│ 20568506 ┆ Team Porp | Dr.   ┆ dr. lame      ┆ /league/nemelee/p ┆ 36.116435 ┆ dr. lame          │
│          ┆ Lame              ┆               ┆ layer/161B23E…    ┆           ┆                   │
│ 20564530 ┆ Greenstach        ┆ greenstach    ┆ /league/nemelee/p ┆ 35.993916 ┆ greenstach        │
│          ┆                   ┆               ┆ layer/0267F6B…    ┆           ┆                   │
│ 20582543 ┆ Ant               ┆ ant           ┆ /league/nemelee/p ┆ 35.631526 ┆ ant               │
│          ┆                   ┆               ┆ layer/5DBCC34…    ┆           ┆                   │
│ 20605019 ┆ Nage              ┆ nage          ┆ /league/nemelee/p ┆ 35.084131 ┆ nage              │
│          ┆                   ┆               ┆ layer/D3B00EC…    ┆           ┆                   │
│ 20567446 ┆ N0va | hc |       ┆ coolslice     ┆ /league/nemelee/p ┆ 35.024779 ┆ coolslice         │
│          ┆ Coolslice         ┆               ┆ layer/583438B…    ┆           ┆                   │
│ 20564582 ┆ Future Shock      ┆ future shock  ┆ /league/nemelee/p ┆ 34.020158 ┆ future shock      │
│          ┆                   ┆               ┆ layer/5CD3DDF…    ┆           ┆                   │
│ 20585636 ┆ hc | saucymain    ┆ saucymain     ┆ /league/nemelee/p ┆ 33.768498 ┆ saucymain         │
│          ┆                   ┆               ┆ layer/2407F41…    ┆           ┆                   │
│ 20565359 ┆ Karils | Conflict ┆ conflict      ┆ /league/nemelee/p ┆ 33.269452 ┆ conflict          │
│          ┆                   ┆               ┆ layer/38A911E…    ┆           ┆                   │
│ 20798969 ┆ Sweat             ┆ sweat         ┆ /league/nemelee/p ┆ 32.880512 ┆ sweat             │
│          ┆                   ┆               ┆ layer/DF3CE0B…    ┆           ┆                   │
│ 20572722 ┆ Shuffle           ┆ shuffle       ┆ /league/nemelee/p ┆ 30.823863 ┆ shuffle           │
│          ┆                   ┆               ┆ layer/D089E7A…    ┆           ┆                   │
│ 20580861 ┆ oz                ┆ oz            ┆ /league/nemelee/p ┆ 30.322893 ┆ oz                │
│          ┆                   ┆               ┆ layer/8FF9A4C…    ┆           ┆                   │
│ 20798985 ┆ Yifu              ┆ yifu          ┆ /league/nemelee/p ┆ 29.455469 ┆ yifu              │
│          ┆                   ┆               ┆ layer/856A527…    ┆           ┆                   │
│ 20592362 ┆ kzgrobb           ┆ kzgrobb       ┆ /league/nemelee/p ┆ 29.387939 ┆ kzgrobb           │
│          ┆                   ┆               ┆ layer/C334C7A…    ┆           ┆                   │
│ 20583175 ┆ zaubermaus        ┆ zaubermaus    ┆ /league/nemelee/p ┆ 29.015436 ┆ zaubermaus        │
│          ┆                   ┆               ┆ layer/66DEE19…    ┆           ┆                   │
│ 20585655 ┆ hc | keke         ┆ keke          ┆ /league/nemelee/p ┆ 28.663466 ┆ keke              │
│          ┆                   ┆               ┆ layer/ACFD51E…    ┆           ┆                   │
│ 20842180 ┆ Nico              ┆ nico          ┆ /league/nemelee/p ┆ 28.538778 ┆ nico              │
│          ┆                   ┆               ┆ layer/D4FE06C…    ┆           ┆                   │
│ 20568131 ┆ HoG | Lati        ┆ lati          ┆ /league/nemelee/p ┆ 28.426864 ┆ lati              │
│          ┆                   ┆               ┆ layer/CA8DB6E…    ┆           ┆                   │
│ 20573810 ┆ DadsAkimbo        ┆ dadsakimbo    ┆ /league/nemelee/p ┆ 28.271189 ┆ dadsakimbo        │
│          ┆                   ┆               ┆ layer/E9FB458…    ┆           ┆                   │
│ 20582608 ┆ Kumatora          ┆ kumatora      ┆ /league/nemelee/p ┆ 28.06187  ┆ kumatora          │
│          ┆                   ┆               ┆ layer/4C51372…    ┆           ┆                   │
│ 20582678 ┆ TeaKay            ┆ teakay        ┆ /league/nemelee/p ┆ 27.917945 ┆ teakay            │
│          ┆                   ┆               ┆ layer/7F2B844…    ┆           ┆                   │
│ 20799153 ┆ lioX0X0           ┆ liox0x0       ┆ /league/nemelee/p ┆ 27.360749 ┆ liox0x0           │
│          ┆                   ┆               ┆ layer/10C85F8…    ┆           ┆                   │
│ 20585659 ┆ hc | Jeep God     ┆ jeep god      ┆ /league/nemelee/p ┆ 26.992038 ┆ jeep god          │
│          ┆                   ┆               ┆ layer/4990C91…    ┆           ┆                   │
│ 20580338 ┆ MOOP              ┆ moop          ┆ /league/nemelee/p ┆ 26.920901 ┆ moop              │
│          ┆                   ┆               ┆ layer/76E2BBC…    ┆           ┆                   │
│ 20580892 ┆ hc | Babs         ┆ babs          ┆ /league/nemelee/p ┆ 26.82861  ┆ babs              │
│          ┆                   ┆               ┆ layer/03D1DA3…    ┆           ┆                   │
│ 20799130 ┆ Sleeper           ┆ sleeper       ┆ /league/nemelee/p ┆ 26.526848 ┆ sleeper           │
│          ┆                   ┆               ┆ layer/44E0B0C…    ┆           ┆                   │
│ 20583462 ┆ hc | Newquake     ┆ newquake      ┆ /league/nemelee/p ┆ 26.330486 ┆ newquake          │
│          ┆                   ┆               ┆ layer/A8962DE…    ┆           ┆                   │
│ 20819954 ┆ Cranberry         ┆ cranberry     ┆ /league/nemelee/p ┆ 25.577538 ┆ cranberry         │
│          ┆                   ┆               ┆ layer/40A32D1…    ┆           ┆                   │
│ 20583615 ┆ Tichinde925       ┆ tichinde925   ┆ /league/nemelee/p ┆ 25.304889 ┆ tichinde925       │
│          ┆                   ┆               ┆ layer/96E6925…    ┆           ┆                   │
│ 20583582 ┆ bleop             ┆ bleop         ┆ /league/nemelee/p ┆ 25.299188 ┆ bleop             │
│          ┆                   ┆               ┆ layer/9DABAEA…    ┆           ┆                   │
│ 20799010 ┆ Rarik             ┆ rarik         ┆ /league/nemelee/p ┆ 25.298521 ┆ rarik             │
│          ┆                   ┆               ┆ layer/FAD5940…    ┆           ┆                   │
│ 20580544 ┆ Vexoskeleton      ┆ vexoskeleton  ┆ /league/nemelee/p ┆ 25.027049 ┆ vexoskeleton      │
│          ┆                   ┆               ┆ layer/96818C5…    ┆           ┆                   │
│ 20587379 ┆ Raf               ┆ raf           ┆ /league/nemelee/p ┆ 24.688363 ┆ raf               │
│          ┆                   ┆               ┆ layer/4A000A5…    ┆           ┆                   │
│ 20580613 ┆ Andrew            ┆ andrew        ┆ /league/nemelee/p ┆ 24.587435 ┆ andrew            │
│          ┆                   ┆               ┆ layer/2029BBF…    ┆           ┆                   │
│ 20582996 ┆ hc | pluto        ┆ pluto         ┆ /league/nemelee/p ┆ 24.241924 ┆ pluto             │
│          ┆                   ┆               ┆ layer/25B1368…    ┆           ┆                   │
│ 20809261 ┆ Downey            ┆ downey        ┆ /league/nemelee/p ┆ 23.8963   ┆ downey            │
│          ┆                   ┆               ┆ layer/A749F70…    ┆           ┆                   │
│ 20793586 ┆ Qwerty            ┆ qwerty        ┆ /league/nemelee/p ┆ 23.887112 ┆ qwerty            │
│          ┆                   ┆               ┆ layer/19B79D7…    ┆           ┆                   │
│ 20824917 ┆ c0 | Monochrome   ┆ monochrome    ┆ /league/nemelee/p ┆ 23.842565 ┆ monochrome        │
│          ┆                   ┆               ┆ layer/849E9B3…    ┆           ┆                   │
│ 20599180 ┆ UML | Blip Blip   ┆ blip blip you ┆ /league/nemelee/p ┆ 23.362657 ┆ blip blip you dip │
│          ┆ You Dip           ┆ dip           ┆ layer/FFB21E9…    ┆           ┆                   │
│ 20591181 ┆ GioIzHawt         ┆ gioizhawt     ┆ /league/nemelee/p ┆ 23.355918 ┆ gioizhawt         │
│          ┆                   ┆               ┆ layer/0D5C264…    ┆           ┆                   │
│ 20581466 ┆ supremelol        ┆ supremelol    ┆ /league/nemelee/p ┆ 23.26504  ┆ supremelol        │
│          ┆                   ┆               ┆ layer/5B24A2E…    ┆           ┆                   │
│ 20798950 ┆ Chimp's Friend |  ┆ saltzy        ┆ /league/nemelee/p ┆ 22.727872 ┆ saltzy            │
│          ┆ Saltzy            ┆               ┆ layer/68EDB09…    ┆           ┆                   │
│ 20842018 ┆ Wolf              ┆ wolf          ┆ /league/nemelee/p ┆ 22.704041 ┆ wolf              │
│          ┆                   ┆               ┆ layer/3C69A05…    ┆           ┆                   │
│ 20798957 ┆ Rekzuh            ┆ rekzuh        ┆ /league/nemelee/p ┆ 21.75522  ┆ rekzuh            │
│          ┆                   ┆               ┆ layer/B6C114A…    ┆           ┆                   │
│ 20855091 ┆ Sabriel           ┆ sabriel       ┆ /league/nemelee/p ┆ 21.330126 ┆ sabriel           │
│          ┆                   ┆               ┆ layer/2A4CD87…    ┆           ┆                   │
│ 20582798 ┆ cynics            ┆ cynics        ┆ /league/nemelee/p ┆ 21.326465 ┆ cynics            │
│          ┆                   ┆               ┆ layer/548EE2F…    ┆           ┆                   │
│ 20588253 ┆ Duhaime           ┆ duhaime       ┆ /league/nemelee/p ┆ 20.242732 ┆ duhaime           │
│          ┆                   ┆               ┆ layer/5DB6859…    ┆           ┆                   │
│ 20603036 ┆ N0va | WAS | N0va ┆ n0va          ┆ /league/nemelee/p ┆ 19.170516 ┆ n0va              │
│          ┆                   ┆               ┆ layer/83E362A…    ┆           ┆                   │
│ 20586596 ┆ Desmond           ┆ desmond       ┆ /league/nemelee/p ┆ 19.134376 ┆ desmond           │
│          ┆                   ┆               ┆ layer/D8F2E00…    ┆           ┆                   │
│ 20814931 ┆ zip zip           ┆ zip zip       ┆ /league/nemelee/p ┆ 19.113027 ┆ zip zip           │
│          ┆                   ┆               ┆ layer/35C481B…    ┆           ┆                   │
│ 20595805 ┆ bfu               ┆ bfu           ┆ /league/nemelee/p ┆ 18.710744 ┆ bfu               │
│          ┆                   ┆               ┆ layer/E8A5E25…    ┆           ┆                   │
│ 20852276 ┆ DarkCloud         ┆ darkcloud     ┆ /league/nemelee/p ┆ 18.649854 ┆ darkcloud         │
│          ┆                   ┆               ┆ layer/2882D19…    ┆           ┆                   │
│ 20826451 ┆ Blueish |         ┆ chanterelle   ┆ /league/nemelee/p ┆ 18.372186 ┆ chanterelle       │
│          ┆ Chanterelle       ┆               ┆ layer/B952D90…    ┆           ┆                   │
│ 20825257 ┆ RedbulSuprnova |  ┆ pépinocreme   ┆ /league/nemelee/p ┆ 17.956992 ┆ pépinocreme       │
│          ┆ PépiNoCreme       ┆               ┆ layer/E22038C…    ┆           ┆                   │
│ 20583937 ┆ NEU | cybert      ┆ cybert        ┆ /league/nemelee/p ┆ 17.430381 ┆ cybert            │
│          ┆                   ┆               ┆ layer/AA77A6C…    ┆           ┆                   │
│ 20600643 ┆ M.SKITTLE         ┆ m.skittle     ┆ /league/nemelee/p ┆ 17.376103 ┆ m.skittle         │
│          ┆                   ┆               ┆ layer/916CB65…    ┆           ┆                   │
│ 20580575 ┆ Juicebox          ┆ juicebox      ┆ /league/nemelee/p ┆ 17.112687 ┆ juicebox          │
│          ┆                   ┆               ┆ layer/369832B…    ┆           ┆                   │
│ 20825426 ┆ kaimen            ┆ kaimen        ┆ /league/nemelee/p ┆ 16.941645 ┆ kaimen            │
│          ┆                   ┆               ┆ layer/FAEB84E…    ┆           ┆                   │
│ 20801241 ┆ nikhil            ┆ nikhil        ┆ /league/nemelee/p ┆ 16.638701 ┆ nikhil            │
│          ┆                   ┆               ┆ layer/CB33312…    ┆           ┆                   │
│ 20596638 ┆ coinstar          ┆ coinstar      ┆ /league/nemelee/p ┆ 15.688436 ┆ coinstar          │
│          ┆                   ┆               ┆ layer/8CB0729…    ┆           ┆                   │
│ 20583833 ┆ wub               ┆ wub           ┆ /league/nemelee/p ┆ 15.232515 ┆ wub               │
│          ┆                   ┆               ┆ layer/9AA4F7A…    ┆           ┆                   │
│ 20825608 ┆ SIX | Embry       ┆ embry         ┆ /league/nemelee/p ┆ 15.230232 ┆ embry             │
│          ┆                   ┆               ┆ layer/320B476…    ┆           ┆                   │
│ 20587334 ┆ Essence           ┆ essence       ┆ /league/nemelee/p ┆ 14.144929 ┆ essence           │
│          ┆                   ┆               ┆ layer/B26F01A…    ┆           ┆                   │
│ 20580944 ┆ Rose | Blue       ┆ blue velvet   ┆ /league/nemelee/p ┆ 14.012004 ┆ blue velvet       │
│          ┆ Velvet            ┆               ┆ layer/35388C6…    ┆           ┆                   │
│ 20581475 ┆ oliver            ┆ oliver        ┆ /league/nemelee/p ┆ 12.605135 ┆ oliver            │
│          ┆                   ┆               ┆ layer/E65EF74…    ┆           ┆                   │
│ 20825651 ┆ AFMCX | Lermonz   ┆ lermonz       ┆ /league/nemelee/p ┆ 12.375902 ┆ lermonz           │
│          ┆                   ┆               ┆ layer/47DEFF2…    ┆           ┆                   │
│ 20580547 ┆ Exarch            ┆ exarch        ┆ /league/nemelee/p ┆ 10.021742 ┆ exarch            │
│          ┆                   ┆               ┆ layer/BD62470…    ┆           ┆                   │
│ 20587511 ┆ Groggy            ┆ groggy        ┆ /league/nemelee/p ┆ 9.767211  ┆ groggy            │
│          ┆                   ┆               ┆ layer/B3CECD7…    ┆           ┆                   │
│ 20792263 ┆ Roughnut29        ┆ roughnut29    ┆ /league/nemelee/p ┆ 7.889988  ┆ roughnut29        │
│          ┆                   ┆               ┆ layer/3E6CDF6…    ┆           ┆                   │
│ 20802361 ┆ brennan           ┆ brennan       ┆ /league/nemelee/p ┆ 7.718873  ┆ brennan           │
│          ┆                   ┆               ┆ layer/5F2DF4E…    ┆           ┆                   │
│ 20597338 ┆ N0va |            ┆ breathlessx22 ┆ /league/nemelee/p ┆ 7.051499  ┆ breathlessx22     │
│          ┆ Breathlessx22     ┆               ┆ layer/EC56A2A…    ┆           ┆                   │
│ 20852388 ┆ BU | BBron        ┆ bbron         ┆ null              ┆ 0.0       ┆ null              │
│ 20583229 ┆ hc | chery*       ┆ chery*        ┆ null              ┆ 0.0       ┆ null              │
│ 20854858 ┆ sfy | LordTet     ┆ lordtet       ┆ null              ┆ 0.0       ┆ null              │
│ 20573757 ┆ Comcast | The     ┆ the covecare  ┆ null              ┆ 0.0       ┆ null              │
│          ┆ CoveCare Scare    ┆ scare         ┆                   ┆           ┆                   │
│ 20803764 ┆ Dominion          ┆ dominion      ┆ null              ┆ 0.0       ┆ null              │
│ 20825653 ┆ ICSP | s1matic    ┆ s1matic       ┆ null              ┆ 0.0       ┆ null              │
│ 20851915 ┆ Wishy             ┆ wishy         ┆ null              ┆ 0.0       ┆ null              │
│ 20838313 ┆ PRIONBOIL         ┆ prionboil     ┆ null              ┆ 0.0       ┆ null              │
│ 20852205 ┆ MattDotZeb        ┆ mattdotzeb    ┆ null              ┆ 0.0       ┆ null              │
│ 20583420 ┆ stir fried        ┆ stir fried    ┆ null              ┆ 0.0       ┆ null              │
└──────────┴───────────────────┴───────────────┴───────────────────┴───────────┴───────────────────┘

In [110]:
entrant_seeding = (
    entrant_ratings
    .sort('rating', descending=True)
    .with_row_index('seed_num')
    .with_columns(pl.col('seed_num') + 1)
)
entrant_seeding

shape: (96, 7)
┌──────────┬──────────┬────────────────┬───────────────┬───────────────┬───────────┬───────────────┐
│ seed_num ┆ id       ┆ name           ┆ gamertag      ┆ url           ┆ rating    ┆ tag           │
│ ---      ┆ ---      ┆ ---            ┆ ---           ┆ ---           ┆ ---       ┆ ---           │
│ u32      ┆ i64      ┆ str            ┆ str           ┆ str           ┆ f64       ┆ str           │
╞══════════╪══════════╪════════════════╪═══════════════╪═══════════════╪═══════════╪═══════════════╡
│ 1        ┆ 20564252 ┆ MATE | Kalvar  ┆ kalvar        ┆ /league/nemel ┆ 43.762813 ┆ kalvar        │
│          ┆          ┆                ┆               ┆ ee/player/C20 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 6957…         ┆           ┆               │
│ 2        ┆ 20564369 ┆ bonfire10      ┆ bonfire10     ┆ /league/nemel ┆ 42.003164 ┆ bonfire10     │
│          ┆          ┆                ┆               ┆ ee/player/C9B ┆           ┆               │
│          ┆          ┆                ┆               ┆ 8492…         ┆           ┆               │
│ 3        ┆ 20564347 ┆ glock in my    ┆ glock in my   ┆ /league/nemel ┆ 39.884903 ┆ glock in my   │
│          ┆          ┆ toyota         ┆ toyota        ┆ ee/player/1FE ┆           ┆ toyota        │
│          ┆          ┆                ┆               ┆ 504A…         ┆           ┆               │
│ 4        ┆ 20567819 ┆ Project        ┆ project       ┆ /league/nemel ┆ 39.53775  ┆ project       │
│          ┆          ┆                ┆               ┆ ee/player/552 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 03EA…         ┆           ┆               │
│ 5        ┆ 20564510 ┆ Ember          ┆ ember         ┆ /league/nemel ┆ 39.526006 ┆ ember         │
│          ┆          ┆                ┆               ┆ ee/player/10F ┆           ┆               │
│          ┆          ┆                ┆               ┆ 6134…         ┆           ┆               │
│ 6        ┆ 20595089 ┆ Q              ┆ q             ┆ /league/nemel ┆ 39.371221 ┆ q             │
│          ┆          ┆                ┆               ┆ ee/player/5C1 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 9CFD…         ┆           ┆               │
│ 7        ┆ 20763728 ┆ YWRM | Q       ┆ q             ┆ /league/nemel ┆ 39.371221 ┆ q             │
│          ┆          ┆                ┆               ┆ ee/player/5C1 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 9CFD…         ┆           ┆               │
│ 8        ┆ 20564883 ┆ Hyouka |       ┆ nairial       ┆ /league/nemel ┆ 38.907933 ┆ nairial       │
│          ┆          ┆ Nairial        ┆               ┆ ee/player/391 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 80F6…         ┆           ┆               │
│ 9        ┆ 20602379 ┆ $G|MP | Bank   ┆ bank          ┆ /league/nemel ┆ 38.823131 ┆ bank          │
│          ┆          ┆                ┆               ┆ ee/player/E85 ┆           ┆               │
│          ┆          ┆                ┆               ┆ EE0F…         ┆           ┆               │
│ 10       ┆ 20564827 ┆ HoG | Arty     ┆ arty          ┆ /league/nemel ┆ 38.74196  ┆ arty          │
│          ┆          ┆                ┆               ┆ ee/player/CEB ┆           ┆               │
│          ┆          ┆                ┆               ┆ CAD4…         ┆           ┆               │
│ 11       ┆ 20596511 ┆ Coffee         ┆ coffee        ┆ /league/nemel ┆ 38.699126 ┆ coffee        │
│          ┆          ┆                ┆               ┆ ee/player/254 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 79C6…         ┆           ┆               │
│ 12       ┆ 20581997 ┆ Tommy          ┆ tommy         ┆ /league/nemel ┆ 38.407676 ┆ tommy         │
│          ┆          ┆                ┆               ┆ ee/player/353 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 0B49…         ┆           ┆               │
│ 13       ┆ 20794076 ┆ eveningstar    ┆ eveningstar   ┆ /league/nemel ┆ 38.216794 ┆ eveningstar   │
│          ┆          ┆                ┆               ┆ ee/player/F3F ┆           ┆               │
│          ┆          ┆                ┆               ┆ CF46…         ┆           ┆               │
│ 14       ┆ 20564432 ┆ Golden         ┆ golden        ┆ /league/nemel ┆ 38.103436 ┆ golden        │
│          ┆          ┆                ┆               ┆ ee/player/CC9 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 99B8…         ┆           ┆               │
│ 15       ┆ 20698945 ┆ DrEsportstTeam ┆ eduporp       ┆ /league/nemel ┆ 37.224269 ┆ eduporp       │
│          ┆          ┆ | EduPorp      ┆               ┆ ee/player/FB1 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 22D4…         ┆           ┆               │
│ 16       ┆ 20568692 ┆ heeg | meep    ┆ meep          ┆ /league/nemel ┆ 36.874359 ┆ meep          │
│          ┆          ┆                ┆               ┆ ee/player/0C1 ┆           ┆               │
│          ┆          ┆                ┆               ┆ E5B6…         ┆           ┆               │
│ 17       ┆ 20568506 ┆ Team Porp |    ┆ dr. lame      ┆ /league/nemel ┆ 36.116435 ┆ dr. lame      │
│          ┆          ┆ Dr. Lame       ┆               ┆ ee/player/161 ┆           ┆               │
│          ┆          ┆                ┆               ┆ B23E…         ┆           ┆               │
│ 18       ┆ 20564530 ┆ Greenstach     ┆ greenstach    ┆ /league/nemel ┆ 35.993916 ┆ greenstach    │
│          ┆          ┆                ┆               ┆ ee/player/026 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 7F6B…         ┆           ┆               │
│ 19       ┆ 20582543 ┆ Ant            ┆ ant           ┆ /league/nemel ┆ 35.631526 ┆ ant           │
│          ┆          ┆                ┆               ┆ ee/player/5DB ┆           ┆               │
│          ┆          ┆                ┆               ┆ CC34…         ┆           ┆               │
│ 20       ┆ 20605019 ┆ Nage           ┆ nage          ┆ /league/nemel ┆ 35.084131 ┆ nage          │
│          ┆          ┆                ┆               ┆ ee/player/D3B ┆           ┆               │
│          ┆          ┆                ┆               ┆ 00EC…         ┆           ┆               │
│ 21       ┆ 20567446 ┆ N0va | hc |    ┆ coolslice     ┆ /league/nemel ┆ 35.024779 ┆ coolslice     │
│          ┆          ┆ Coolslice      ┆               ┆ ee/player/583 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 438B…         ┆           ┆               │
│ 22       ┆ 20564582 ┆ Future Shock   ┆ future shock  ┆ /league/nemel ┆ 34.020158 ┆ future shock  │
│          ┆          ┆                ┆               ┆ ee/player/5CD ┆           ┆               │
│          ┆          ┆                ┆               ┆ 3DDF…         ┆           ┆               │
│ 23       ┆ 20585636 ┆ hc | saucymain ┆ saucymain     ┆ /league/nemel ┆ 33.768498 ┆ saucymain     │
│          ┆          ┆                ┆               ┆ ee/player/240 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 7F41…         ┆           ┆               │
│ 24       ┆ 20565359 ┆ Karils |       ┆ conflict      ┆ /league/nemel ┆ 33.269452 ┆ conflict      │
│          ┆          ┆ Conflict       ┆               ┆ ee/player/38A ┆           ┆               │
│          ┆          ┆                ┆               ┆ 911E…         ┆           ┆               │
│ 25       ┆ 20798969 ┆ Sweat          ┆ sweat         ┆ /league/nemel ┆ 32.880512 ┆ sweat         │
│          ┆          ┆                ┆               ┆ ee/player/DF3 ┆           ┆               │
│          ┆          ┆                ┆               ┆ CE0B…         ┆           ┆               │
│ 26       ┆ 20572722 ┆ Shuffle        ┆ shuffle       ┆ /league/nemel ┆ 30.823863 ┆ shuffle       │
│          ┆          ┆                ┆               ┆ ee/player/D08 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 9E7A…         ┆           ┆               │
│ 27       ┆ 20580861 ┆ oz             ┆ oz            ┆ /league/nemel ┆ 30.322893 ┆ oz            │
│          ┆          ┆                ┆               ┆ ee/player/8FF ┆           ┆               │
│          ┆          ┆                ┆               ┆ 9A4C…         ┆           ┆               │
│ 28       ┆ 20798985 ┆ Yifu           ┆ yifu          ┆ /league/nemel ┆ 29.455469 ┆ yifu          │
│          ┆          ┆                ┆               ┆ ee/player/856 ┆           ┆               │
│          ┆          ┆                ┆               ┆ A527…         ┆           ┆               │
│ 29       ┆ 20592362 ┆ kzgrobb        ┆ kzgrobb       ┆ /league/nemel ┆ 29.387939 ┆ kzgrobb       │
│          ┆          ┆                ┆               ┆ ee/player/C33 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 4C7A…         ┆           ┆               │
│ 30       ┆ 20583175 ┆ zaubermaus     ┆ zaubermaus    ┆ /league/nemel ┆ 29.015436 ┆ zaubermaus    │
│          ┆          ┆                ┆               ┆ ee/player/66D ┆           ┆               │
│          ┆          ┆                ┆               ┆ EE19…         ┆           ┆               │
│ 31       ┆ 20585655 ┆ hc | keke      ┆ keke          ┆ /league/nemel ┆ 28.663466 ┆ keke          │
│          ┆          ┆                ┆               ┆ ee/player/ACF ┆           ┆               │
│          ┆          ┆                ┆               ┆ D51E…         ┆           ┆               │
│ 32       ┆ 20842180 ┆ Nico           ┆ nico          ┆ /league/nemel ┆ 28.538778 ┆ nico          │
│          ┆          ┆                ┆               ┆ ee/player/D4F ┆           ┆               │
│          ┆          ┆                ┆               ┆ E06C…         ┆           ┆               │
│ 33       ┆ 20568131 ┆ HoG | Lati     ┆ lati          ┆ /league/nemel ┆ 28.426864 ┆ lati          │
│          ┆          ┆                ┆               ┆ ee/player/CA8 ┆           ┆               │
│          ┆          ┆                ┆               ┆ DB6E…         ┆           ┆               │
│ 34       ┆ 20573810 ┆ DadsAkimbo     ┆ dadsakimbo    ┆ /league/nemel ┆ 28.271189 ┆ dadsakimbo    │
│          ┆          ┆                ┆               ┆ ee/player/E9F ┆           ┆               │
│          ┆          ┆                ┆               ┆ B458…         ┆           ┆               │
│ 35       ┆ 20582608 ┆ Kumatora       ┆ kumatora      ┆ /league/nemel ┆ 28.06187  ┆ kumatora      │
│          ┆          ┆                ┆               ┆ ee/player/4C5 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 1372…         ┆           ┆               │
│ 36       ┆ 20582678 ┆ TeaKay         ┆ teakay        ┆ /league/nemel ┆ 27.917945 ┆ teakay        │
│          ┆          ┆                ┆               ┆ ee/player/7F2 ┆           ┆               │
│          ┆          ┆                ┆               ┆ B844…         ┆           ┆               │
│ 37       ┆ 20799153 ┆ lioX0X0        ┆ liox0x0       ┆ /league/nemel ┆ 27.360749 ┆ liox0x0       │
│          ┆          ┆                ┆               ┆ ee/player/10C ┆           ┆               │
│          ┆          ┆                ┆               ┆ 85F8…         ┆           ┆               │
│ 38       ┆ 20585659 ┆ hc | Jeep God  ┆ jeep god      ┆ /league/nemel ┆ 26.992038 ┆ jeep god      │
│          ┆          ┆                ┆               ┆ ee/player/499 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 0C91…         ┆           ┆               │
│ 39       ┆ 20580338 ┆ MOOP           ┆ moop          ┆ /league/nemel ┆ 26.920901 ┆ moop          │
│          ┆          ┆                ┆               ┆ ee/player/76E ┆           ┆               │
│          ┆          ┆                ┆               ┆ 2BBC…         ┆           ┆               │
│ 40       ┆ 20580892 ┆ hc | Babs      ┆ babs          ┆ /league/nemel ┆ 26.82861  ┆ babs          │
│          ┆          ┆                ┆               ┆ ee/player/03D ┆           ┆               │
│          ┆          ┆                ┆               ┆ 1DA3…         ┆           ┆               │
│ 41       ┆ 20799130 ┆ Sleeper        ┆ sleeper       ┆ /league/nemel ┆ 26.526848 ┆ sleeper       │
│          ┆          ┆                ┆               ┆ ee/player/44E ┆           ┆               │
│          ┆          ┆                ┆               ┆ 0B0C…         ┆           ┆               │
│ 42       ┆ 20583462 ┆ hc | Newquake  ┆ newquake      ┆ /league/nemel ┆ 26.330486 ┆ newquake      │
│          ┆          ┆                ┆               ┆ ee/player/A89 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 62DE…         ┆           ┆               │
│ 43       ┆ 20819954 ┆ Cranberry      ┆ cranberry     ┆ /league/nemel ┆ 25.577538 ┆ cranberry     │
│          ┆          ┆                ┆               ┆ ee/player/40A ┆           ┆               │
│          ┆          ┆                ┆               ┆ 32D1…         ┆           ┆               │
│ 44       ┆ 20583615 ┆ Tichinde925    ┆ tichinde925   ┆ /league/nemel ┆ 25.304889 ┆ tichinde925   │
│          ┆          ┆                ┆               ┆ ee/player/96E ┆           ┆               │
│          ┆          ┆                ┆               ┆ 6925…         ┆           ┆               │
│ 45       ┆ 20583582 ┆ bleop          ┆ bleop         ┆ /league/nemel ┆ 25.299188 ┆ bleop         │
│          ┆          ┆                ┆               ┆ ee/player/9DA ┆           ┆               │
│          ┆          ┆                ┆               ┆ BAEA…         ┆           ┆               │
│ 46       ┆ 20799010 ┆ Rarik          ┆ rarik         ┆ /league/nemel ┆ 25.298521 ┆ rarik         │
│          ┆          ┆                ┆               ┆ ee/player/FAD ┆           ┆               │
│          ┆          ┆                ┆               ┆ 5940…         ┆           ┆               │
│ 47       ┆ 20580544 ┆ Vexoskeleton   ┆ vexoskeleton  ┆ /league/nemel ┆ 25.027049 ┆ vexoskeleton  │
│          ┆          ┆                ┆               ┆ ee/player/968 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 18C5…         ┆           ┆               │
│ 48       ┆ 20587379 ┆ Raf            ┆ raf           ┆ /league/nemel ┆ 24.688363 ┆ raf           │
│          ┆          ┆                ┆               ┆ ee/player/4A0 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 00A5…         ┆           ┆               │
│ 49       ┆ 20580613 ┆ Andrew         ┆ andrew        ┆ /league/nemel ┆ 24.587435 ┆ andrew        │
│          ┆          ┆                ┆               ┆ ee/player/202 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 9BBF…         ┆           ┆               │
│ 50       ┆ 20582996 ┆ hc | pluto     ┆ pluto         ┆ /league/nemel ┆ 24.241924 ┆ pluto         │
│          ┆          ┆                ┆               ┆ ee/player/25B ┆           ┆               │
│          ┆          ┆                ┆               ┆ 1368…         ┆           ┆               │
│ 51       ┆ 20809261 ┆ Downey         ┆ downey        ┆ /league/nemel ┆ 23.8963   ┆ downey        │
│          ┆          ┆                ┆               ┆ ee/player/A74 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 9F70…         ┆           ┆               │
│ 52       ┆ 20793586 ┆ Qwerty         ┆ qwerty        ┆ /league/nemel ┆ 23.887112 ┆ qwerty        │
│          ┆          ┆                ┆               ┆ ee/player/19B ┆           ┆               │
│          ┆          ┆                ┆               ┆ 79D7…         ┆           ┆               │
│ 53       ┆ 20824917 ┆ c0 |           ┆ monochrome    ┆ /league/nemel ┆ 23.842565 ┆ monochrome    │
│          ┆          ┆ Monochrome     ┆               ┆ ee/player/849 ┆           ┆               │
│          ┆          ┆                ┆               ┆ E9B3…         ┆           ┆               │
│ 54       ┆ 20599180 ┆ UML | Blip     ┆ blip blip you ┆ /league/nemel ┆ 23.362657 ┆ blip blip you │
│          ┆          ┆ Blip You Dip   ┆ dip           ┆ ee/player/FFB ┆           ┆ dip           │
│          ┆          ┆                ┆               ┆ 21E9…         ┆           ┆               │
│ 55       ┆ 20591181 ┆ GioIzHawt      ┆ gioizhawt     ┆ /league/nemel ┆ 23.355918 ┆ gioizhawt     │
│          ┆          ┆                ┆               ┆ ee/player/0D5 ┆           ┆               │
│          ┆          ┆                ┆               ┆ C264…         ┆           ┆               │
│ 56       ┆ 20581466 ┆ supremelol     ┆ supremelol    ┆ /league/nemel ┆ 23.26504  ┆ supremelol    │
│          ┆          ┆                ┆               ┆ ee/player/5B2 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 4A2E…         ┆           ┆               │
│ 57       ┆ 20798950 ┆ Chimp's Friend ┆ saltzy        ┆ /league/nemel ┆ 22.727872 ┆ saltzy        │
│          ┆          ┆ | Saltzy       ┆               ┆ ee/player/68E ┆           ┆               │
│          ┆          ┆                ┆               ┆ DB09…         ┆           ┆               │
│ 58       ┆ 20842018 ┆ Wolf           ┆ wolf          ┆ /league/nemel ┆ 22.704041 ┆ wolf          │
│          ┆          ┆                ┆               ┆ ee/player/3C6 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 9A05…         ┆           ┆               │
│ 59       ┆ 20798957 ┆ Rekzuh         ┆ rekzuh        ┆ /league/nemel ┆ 21.75522  ┆ rekzuh        │
│          ┆          ┆                ┆               ┆ ee/player/B6C ┆           ┆               │
│          ┆          ┆                ┆               ┆ 114A…         ┆           ┆               │
│ 60       ┆ 20855091 ┆ Sabriel        ┆ sabriel       ┆ /league/nemel ┆ 21.330126 ┆ sabriel       │
│          ┆          ┆                ┆               ┆ ee/player/2A4 ┆           ┆               │
│          ┆          ┆                ┆               ┆ CD87…         ┆           ┆               │
│ 61       ┆ 20582798 ┆ cynics         ┆ cynics        ┆ /league/nemel ┆ 21.326465 ┆ cynics        │
│          ┆          ┆                ┆               ┆ ee/player/548 ┆           ┆               │
│          ┆          ┆                ┆               ┆ EE2F…         ┆           ┆               │
│ 62       ┆ 20588253 ┆ Duhaime        ┆ duhaime       ┆ /league/nemel ┆ 20.242732 ┆ duhaime       │
│          ┆          ┆                ┆               ┆ ee/player/5DB ┆           ┆               │
│          ┆          ┆                ┆               ┆ 6859…         ┆           ┆               │
│ 63       ┆ 20603036 ┆ N0va | WAS |   ┆ n0va          ┆ /league/nemel ┆ 19.170516 ┆ n0va          │
│          ┆          ┆ N0va           ┆               ┆ ee/player/83E ┆           ┆               │
│          ┆          ┆                ┆               ┆ 362A…         ┆           ┆               │
│ 64       ┆ 20586596 ┆ Desmond        ┆ desmond       ┆ /league/nemel ┆ 19.134376 ┆ desmond       │
│          ┆          ┆                ┆               ┆ ee/player/D8F ┆           ┆               │
│          ┆          ┆                ┆               ┆ 2E00…         ┆           ┆               │

# Export seeding to start gg

In [51]:
# Query to get phase IDs for Melee Singles event
phases_query = gql("""
query EventPhases($eventId: ID!) {
    event(id: $eventId) {
        phases {
            id
            name
            numSeeds
        }
    }
}
""")

phases_variables = {"eventId": melee_singles_id}

try:
        phases_result = client.execute(phases_query, variable_values=phases_variables)
        print(json.dumps(phases_result, indent=2))
except Exception as e:
        print("Error fetching phases:", e)

phase_id = phases_result['event']['phases'][0]['id']
print(f'phase id: {phase_id}')

{
  "event": {
    "phases": [
      {
        "id": 2033907,
        "name": "Bracket",
        "numSeeds": 18
      }
    ]
  }
}
phase id: 2033907

In [52]:
# ...existing code...

# 1. Fetch seeds for the phase
seeds_query = gql("""
query PhaseSeeds($phaseId: ID!) {
  phase(id: $phaseId) {
    seeds(query: {perPage: 512}) {
      nodes {
        id
        entrant {
          id
        }
      }
    }
  }
}
""")
seeds_result = client.execute(seeds_query, variable_values={"phaseId": phase_id})
seed_nodes = seeds_result["phase"]["seeds"]["nodes"]
entrantid_to_seedid = {seed["entrant"]["id"]: seed["id"] for seed in seed_nodes}

# 2. Prepare seed mapping using correct seedId
seed_mapping = []
for row in entrant_seeding.iter_rows(named=True):
    entrant_id = int(row["id"])
    seed_id = entrantid_to_seedid.get(entrant_id)
    if seed_id:
        seed_mapping.append({
            "seedId": seed_id,
            "seedNum": row["seed_num"],
        })
    else:
        print(f"Warning: No seed found for entrant {entrant_id}")

print(f"Importing {len(seed_mapping)} seeds to phase {phase_id}...")

Importing 18 seeds to phase 2033907...

In [53]:
entrant_seeding = (
    entrant_seeding
    .with_columns(pl.col('id').map_elements(lambda x: entrantid_to_seedid.get(x, None)).alias('seed_id'))
)

/tmp/ipykernel_6676/1705157941.py:3: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
  .with_columns(pl.col('id').map_elements(lambda x: entrantid_to_seedid.get(x, None)).alias('seed_id'))

In [54]:
# Prepare seed mapping from entrant_ratings for the phase
seed_mapping = []
for row in entrant_seeding.iter_rows(named=True):
    seed_mapping.append({
        "seedId": row["seed_id"],
        "seedNum": row['seed_num'],
    })

print(f"Importing {len(seed_mapping)} seeds to phase {phase_id}...")

mutation = gql("""
mutation UpdatePhaseSeeding($phaseId: ID!, $seedMapping: [UpdatePhaseSeedInfo]!) {
  updatePhaseSeeding(phaseId: $phaseId, seedMapping: $seedMapping) {
    id
  }
}
""")

params = {
    "phaseId": phase_id,
    "seedMapping": seed_mapping,
}

try:
    result = client.execute(mutation, variable_values=params)
    print('Success!')
    print(result)
except Exception as e:
    print('Error:', e)

Importing 18 seeds to phase 2033907...
Success!
{'updatePhaseSeeding': {'id': 2033907}}

# view previous tournaments by player

In [111]:
player = 'mattdotzeb'

In [112]:
from IPython.display import display, HTML

def display_side_by_side(*args, titles=('',)):
    html_str = ''
    if len(titles) > 0:
        html_str += '<div style="display:flex">'
    for df, title in zip(args, titles + ('',) * (len(args) - len(titles))):
        html_str += '<div style="margin-right:20px">'
        if title:
            html_str += f'<h2>{title}</h2>'
        html_str += df.to_html()
        html_str += '</div>'
    html_str += '</div>'
    display(HTML(html_str))

In [113]:
matches = pl.read_csv('data/matches-with-ratings.csv')

In [117]:
last_n_matches = (
    matches
    .filter(
        pl.col('winner').str.to_lowercase().str.contains(player.lower()) |
        pl.col('loser').str.to_lowercase().str.contains(player.lower())
    )
    .sort('tournament_date', 'encounter_id', descending=True)
    .head(40)
)
losses = (
    last_n_matches
    .filter(pl.col('loser').str.to_lowercase().str.contains(player.lower()))
    .select(
        pl.col('winner').alias('tag'),
        'winner_rating',
        'tournament_name',
        'tournament_date',
        'loser_score',
    )
    .sort('winner_rating', descending=False)
)
wins = (
    last_n_matches
    .filter(pl.col('winner').str.to_lowercase().str.contains(player.lower()))
    .select(
        pl.col('loser').alias('tag'),
        'loser_rating',
        'tournament_name',
        'tournament_date',
        'winner_score',
    )
    .sort('loser_rating', descending=True)
)
display_side_by_side(
    losses.to_pandas(),
    wins.to_pandas(),
    titles=('Losses', 'Wins')
)