# Get list of entrants

In [16]:
tournament_slug = 'aav'
tournament_slug = 'allston-allstars-vi-1'
tournament_slug = 'ngpr'
event_name = 'Rishi\'s Jungle Jam'
event_name = 'Old School Melee'
event_name = 'Three Character Iron Man'
event_name = 'Melee Redemption'
event_name = 'Melee Singles'

In [17]:
%%bash
source ~/.bashrc

In [18]:
import os
import json
from gql import gql, Client
from gql.transport.requests import RequestsHTTPTransport

auth_token = os.environ['SMASHGG_TOKEN']
api_version = 'alpha'

transport = RequestsHTTPTransport(
    url=f'https://api.start.gg/gql/{api_version}',
    headers={'Authorization': f'Bearer {auth_token}'},
    use_json=True,
)

client = Client(transport=transport, fetch_schema_from_transport=False)

In [19]:
# Define the API endpoint and query for tournament details
query = gql("""
query TournamentQuery($slug: String!) {
    tournament(slug: $slug) {
        id
        name
        city
        state
        countryCode
        startAt
        endAt
        events {
            id
            videogame {
                id
                name
            }
            name
            numEntrants
        }
    }
}
""")

variables = {"slug": tournament_slug}

# Execute the query
try:
        tournament_result = client.execute(query, variable_values=variables)
        print(json.dumps(tournament_result, indent=2))
except Exception as e:
        print("Error fetching tournament details:", e)

{
  "tournament": {
    "id": 893520,
    "name": "New Game Plus Revival 9.21",
    "city": "Boston",
    "state": 3,
    "countryCode": "US",
    "startAt": 1774388700,
    "endAt": 1774411140,
    "events": [
      {
        "id": 1586819,
        "videogame": {
          "id": 1,
          "name": "Super Smash Bros. Melee"
        },
        "name": "Melee Redemption",
        "numEntrants": 0
      },
      {
        "id": 1586818,
        "videogame": {
          "id": 1,
          "name": "Super Smash Bros. Melee"
        },
        "name": "Melee Singles",
        "numEntrants": 36
      },
      {
        "id": 1586821,
        "videogame": {
          "id": 1,
          "name": "Super Smash Bros. Melee"
        },
        "name": "Melee Doubles",
        "numEntrants": 7
      },
      {
        "id": 1586820,
        "videogame": {
          "id": 33602,
          "name": "Project+"
        },
        "name": "Project + Singles",
        "numEntrants": 4
      }
    ]
  }
}

In [20]:
# Extract the event id for "Melee Singles"
events = tournament_result['tournament']['events']
melee_singles_id = next((event['id'] for event in events if event_name in event['name']), None)
print(f"{event_name} Event ID: {melee_singles_id}")

Melee Singles Event ID: 1586818

In [21]:
# Query to get entrants for Melee Singles
entrants_query = gql("""
query EventEntrants($eventId: ID!) {
    event(id: $eventId) {
        entrants(query: {page: 1, perPage: 512}) {
            nodes {
                id
                name
                participants {
                    gamerTag
                    user {
                        slug
                    }
                }
            }
        }
    }
}
""")

entrants_variables = {"eventId": melee_singles_id}

try:
        entrants_result = client.execute(entrants_query, variable_values=entrants_variables)
        print(json.dumps(entrants_result, indent=2))
except Exception as e:
        print("Error fetching entrants:", e)

{
  "event": {
    "entrants": {
      "nodes": [
        {
          "id": 23010981,
          "name": "Bigs",
          "participants": [
            {
              "gamerTag": "Bigs",
              "user": {
                "slug": "user/3b2098c3"
              }
            }
          ]
        },
        {
          "id": 23010976,
          "name": "MOOP",
          "participants": [
            {
              "gamerTag": "MOOP",
              "user": {
                "slug": "user/0d9573f9"
              }
            }
          ]
        },
        {
          "id": 23010849,
          "name": "hc | keke",
          "participants": [
            {
              "gamerTag": "keke",
              "user": {
                "slug": "user/4864af7d"
              }
            }
          ]
        },
        {
          "id": 23010836,
          "name": "RoccoChief",
          "participants": [
            {
              "gamerTag": "RoccoChief",
              "user": {
                "slug": "user/b6e80781"
              }
            }
          ]
        },
        {
          "id": 23010778,
          "name": "hc | Good1ife",
          "participants": [
            {
              "gamerTag": "Good1ife",
              "user": {
                "slug": "user/b00c5480"
              }
            }
          ]
        },
        {
          "id": 23010630,
          "name": "DrillYouu",
          "participants": [
            {
              "gamerTag": "DrillYouu",
              "user": null
            }
          ]
        },
        {
          "id": 23010623,
          "name": "heylayow",
          "participants": [
            {
              "gamerTag": "heylayow",
              "user": null
            }
          ]
        },
        {
          "id": 23010558,
          "name": "hc | PajamaPal",
          "participants": [
            {
              "gamerTag": "PajamaPal",
              "user": {
                "slug": "user/17a303f0"
              }
            }
          ]
        },
        {
          "id": 23010442,
          "name": "RhodeIslandBean",
          "participants": [
            {
              "gamerTag": "RhodeIslandBean",
              "user": {
                "slug": "user/92bc0664"
              }
            }
          ]
        },
        {
          "id": 23010043,
          "name": "hc | Jeep God",
          "participants": [
            {
              "gamerTag": "Jeep God",
              "user": {
                "slug": "user/3e53dd7e"
              }
            }
          ]
        },
        {
          "id": 23009701,
          "name": "sfy | sfy bees",
          "participants": [
            {
              "gamerTag": "sfy bees",
              "user": {
                "slug": "user/aff9eacf"
              }
            }
          ]
        },
        {
          "id": 23009673,
          "name": "Motobug",
          "participants": [
            {
              "gamerTag": "Motobug",
              "user": {
                "slug": "user/82f22ab0"
              }
            }
          ]
        },
        {
          "id": 23009376,
          "name": "joe chemo",
          "participants": [
            {
              "gamerTag": "joe chemo",
              "user": {
                "slug": "user/18d752ee"
              }
            }
          ]
        },
        {
          "id": 23009323,
          "name": "BonkCushy",
          "participants": [
            {
              "gamerTag": "BonkCushy",
              "user": {
                "slug": "user/f6746266"
              }
            }
          ]
        },
        {
          "id": 23009223,
          "name": "Uncle Fraski",
          "participants": [
            {
              "gamerTag": "Uncle Fraski",
              "user": {
                "slug": "user/2529ae12"
              }
            }
          ]
        },
        {
          "id": 23009063,
          "name": "Ant",
          "participants": [
            {
              "gamerTag": "Ant",
              "user": {
                "slug": "user/36e92bc4"
              }
            }
          ]
        },
        {
          "id": 23008995,
          "name": "KBK | ren",
          "participants": [
            {
              "gamerTag": "ren",
              "user": {
                "slug": "user/85e021f4"
              }
            }
          ]
        },
        {
          "id": 23008797,
          "name": "Cheezboom",
          "participants": [
            {
              "gamerTag": "Cheezboom",
              "user": {
                "slug": "user/7645aa42"
              }
            }
          ]
        },
        {
          "id": 23008550,
          "name": "q | Coffee",
          "participants": [
            {
              "gamerTag": "Coffee",
              "user": {
                "slug": "user/7f24e089"
              }
            }
          ]
        },
        {
          "id": 23008529,
          "name": "Byrne",
          "participants": [
            {
              "gamerTag": "Byrne",
              "user": {
                "slug": "user/fc45cec4"
              }
            }
          ]
        },
        {
          "id": 23008488,
          "name": "Frootbat",
          "participants": [
            {
              "gamerTag": "Frootbat",
              "user": {
                "slug": "user/bc953e40"
              }
            }
          ]
        },
        {
          "id": 23008421,
          "name": "Robert WIlliwinkle III",
          "participants": [
            {
              "gamerTag": "Robert WIlliwinkle III",
              "user": {
                "slug": "user/e0679718"
              }
            }
          ]
        },
        {
          "id": 23008232,
          "name": "fng | InDaHouse",
          "participants": [
            {
              "gamerTag": "InDaHouse",
              "user": {
                "slug": "user/01bb7994"
              }
            }
          ]
        },
        {
          "id": 23008215,
          "name": "TSI | coffee",
          "participants": [
            {
              "gamerTag": "coffee",
              "user": {
                "slug": "user/0046c6b3"
              }
            }
          ]
        },
        {
          "id": 23008184,
          "name": "BRamZ",
          "participants": [
            {
              "gamerTag": "BRamZ",
              "user": {
                "slug": "user/0393b9e8"
              }
            }
          ]
        },
        {
          "id": 23008168,
          "name": "Exarch",
          "participants": [
            {
              "gamerTag": "Exarch",
              "user": {
                "slug": "user/8d0e17f7"
              }
            }
          ]
        },
        {
          "id": 23008078,
          "name": "Smokin' That Shit!",
          "participants": [
            {
              "gamerTag": "Smokin' That Shit!",
              "user": {
                "slug": "user/33de7b6f"
              }
            }
          ]
        },
        {
          "id": 23008069,
          "name": "Qwerty",
          "participants": [
            {
              "gamerTag": "Qwerty",
              "user": {
                "slug": "user/b9853b93"
              }
            }
          ]
        },
        {
          "id": 23007357,
          "name": "hc | Babs",
          "participants": [
            {
              "gamerTag": "Babs",
              "user": {
                "slug": "user/17238f3e"
              }
            }
          ]
        },
        {
          "id": 23007345,
          "name": "GuitarLord",
          "participants": [
            {
              "gamerTag": "GuitarLord",
              "user": {
                "slug": "user/f85c4e29"
              }
            }
          ]
        },
        {
          "id": 23007299,
          "name": "CrucialCrazy",
          "participants": [
            {
              "gamerTag": "CrucialCrazy",
              "user": {
                "slug": "user/fb184c22"
              }
            }
          ]
        },
        {
          "id": 23007181,
          "name": "Groggy",
          "participants": [
            {
              "gamerTag": "Groggy",
              "user": {
                "slug": "user/7cfb3282"
              }
            }
          ]
        },
        {
          "id": 23006760,
          "name": "BoratNorad",
          "participants": [
            {
              "gamerTag": "BoratNorad",
              "user": {
                "slug": "user/29fa119a"
              }
            }
          ]
        },
        {
          "id": 23004324,
          "name": "melee.boston | Puunk_",
          "participants": [
            {
              "gamerTag": "Puunk_",
              "user": {
                "slug": "user/fbea21fb"
              }
            }
          ]
        },
        {
          "id": 22998770,
          "name": "Brotherhood | Duffy",
          "participants": [
            {
              "gamerTag": "Duffy",
              "user": {
                "slug": "user/8daaf377"
              }
            }
          ]
        },
        {
          "id": 22991834,
          "name": "zaubermaus",
          "participants": [
            {
              "gamerTag": "zaubermaus",
              "user": {
                "slug": "user/0a76d369"
              }
            }
          ]
        }
      ]
    }
  }
}

In [22]:
import polars as pl

# Extract entrant data and flatten participants' gamerTags

entrant_nodes = entrants_result['event']['entrants']['nodes']
data = []
for entrant in entrant_nodes:
    entrant_id = entrant['id']
    entrant_name = entrant['name']
    # There may be multiple participants per entrant; join their gamerTags with comma
    gamer_tags = [p['gamerTag'] for p in entrant.get('participants', [])]
    gamer_tag = ', '.join(gamer_tags)
    data.append({'id': entrant_id, 'name': entrant_name, 'gamertag': gamer_tag})

entrants = pl.DataFrame(data)
entrants

shape: (36, 3)
┌──────────┬────────────────────────┬────────────────────────┐
│ id       ┆ name                   ┆ gamertag               │
│ ---      ┆ ---                    ┆ ---                    │
│ i64      ┆ str                    ┆ str                    │
╞══════════╪════════════════════════╪════════════════════════╡
│ 23010981 ┆ Bigs                   ┆ Bigs                   │
│ 23010976 ┆ MOOP                   ┆ MOOP                   │
│ 23010849 ┆ hc | keke              ┆ keke                   │
│ 23010836 ┆ RoccoChief             ┆ RoccoChief             │
│ 23010778 ┆ hc | Good1ife          ┆ Good1ife               │
│ 23010630 ┆ DrillYouu              ┆ DrillYouu              │
│ 23010623 ┆ heylayow               ┆ heylayow               │
│ 23010558 ┆ hc | PajamaPal         ┆ PajamaPal              │
│ 23010442 ┆ RhodeIslandBean        ┆ RhodeIslandBean        │
│ 23010043 ┆ hc | Jeep God          ┆ Jeep God               │
│ 23009701 ┆ sfy | sfy bees         ┆ sfy bees               │
│ 23009673 ┆ Motobug                ┆ Motobug                │
│ 23009376 ┆ joe chemo              ┆ joe chemo              │
│ 23009323 ┆ BonkCushy              ┆ BonkCushy              │
│ 23009223 ┆ Uncle Fraski           ┆ Uncle Fraski           │
│ 23009063 ┆ Ant                    ┆ Ant                    │
│ 23008995 ┆ KBK | ren              ┆ ren                    │
│ 23008797 ┆ Cheezboom              ┆ Cheezboom              │
│ 23008550 ┆ q | Coffee             ┆ Coffee                 │
│ 23008529 ┆ Byrne                  ┆ Byrne                  │
│ 23008488 ┆ Frootbat               ┆ Frootbat               │
│ 23008421 ┆ Robert WIlliwinkle III ┆ Robert WIlliwinkle III │
│ 23008232 ┆ fng | InDaHouse        ┆ InDaHouse              │
│ 23008215 ┆ TSI | coffee           ┆ coffee                 │
│ 23008184 ┆ BRamZ                  ┆ BRamZ                  │
│ 23008168 ┆ Exarch                 ┆ Exarch                 │
│ 23008078 ┆ Smokin' That Shit!     ┆ Smokin' That Shit!     │
│ 23008069 ┆ Qwerty                 ┆ Qwerty                 │
│ 23007357 ┆ hc | Babs              ┆ Babs                   │
│ 23007345 ┆ GuitarLord             ┆ GuitarLord             │
│ 23007299 ┆ CrucialCrazy           ┆ CrucialCrazy           │
│ 23007181 ┆ Groggy                 ┆ Groggy                 │
│ 23006760 ┆ BoratNorad             ┆ BoratNorad             │
│ 23004324 ┆ melee.boston | Puunk_  ┆ Puunk_                 │
│ 22998770 ┆ Brotherhood | Duffy    ┆ Duffy                  │
│ 22991834 ┆ zaubermaus             ┆ zaubermaus             │
└──────────┴────────────────────────┴────────────────────────┘

In [23]:
entrant_gamertags = entrants.select(pl.col('gamertag')).to_series().to_list()

# collect seeding

In [24]:
player_ratings = pl.read_parquet('data/player-ratings.parquet')

In [25]:
pl.Config(tbl_rows=100)
entrant_ratings = (
    entrants
    .with_columns(pl.col('gamertag'))
    .join(
        player_ratings
            .with_columns(pl.col('tag').str.split(' | ').list.last()),
        how='full',
        left_on='gamertag',
        right_on='tag',
    )
    #.filter(
    #    (pl.col('tag').str.to_lowercase() == pl.col('gamertag').str.to_lowercase()) |
    #    pl.col('gamertag').is_null()
    #)
    .filter(pl.col('gamertag').is_not_null())
    .sort('rating', descending=True)
    .group_by('id').first()
    .fill_null(0)
    .sort('rating', descending=True)
)
display(entrant_ratings)

shape: (36, 6)
┌──────────┬──────────────────┬──────────────────┬──────────────────┬───────────┬──────────────────┐
│ id       ┆ name             ┆ gamertag         ┆ url              ┆ rating    ┆ tag              │
│ ---      ┆ ---              ┆ ---              ┆ ---              ┆ ---       ┆ ---              │
│ i64      ┆ str              ┆ str              ┆ str              ┆ f64       ┆ str              │
╞══════════╪══════════════════╪══════════════════╪══════════════════╪═══════════╪══════════════════╡
│ 23008215 ┆ TSI | coffee     ┆ coffee           ┆ /league/nemelee/ ┆ 40.230426 ┆ coffee           │
│          ┆                  ┆                  ┆ player/25479C6…  ┆           ┆                  │
│ 23009063 ┆ Ant              ┆ Ant              ┆ /league/nemelee/ ┆ 34.396759 ┆ Ant              │
│          ┆                  ┆                  ┆ player/5DBCC34…  ┆           ┆                  │
│ 23010778 ┆ hc | Good1ife    ┆ Good1ife         ┆ /league/nemelee/ ┆ 32.577395 ┆ Good1ife         │
│          ┆                  ┆                  ┆ player/396A6F1…  ┆           ┆                  │
│ 23008184 ┆ BRamZ            ┆ BRamZ            ┆ /league/nemelee/ ┆ 30.096264 ┆ BRamZ            │
│          ┆                  ┆                  ┆ player/8CB30ED…  ┆           ┆                  │
│ 23009323 ┆ BonkCushy        ┆ BonkCushy        ┆ /league/nemelee/ ┆ 29.72562  ┆ BonkCushy        │
│          ┆                  ┆                  ┆ player/1056255…  ┆           ┆                  │
│ 23009673 ┆ Motobug          ┆ Motobug          ┆ /league/nemelee/ ┆ 29.643181 ┆ Motobug          │
│          ┆                  ┆                  ┆ player/E12030B…  ┆           ┆                  │
│ 22991834 ┆ zaubermaus       ┆ zaubermaus       ┆ /league/nemelee/ ┆ 28.995816 ┆ zaubermaus       │
│          ┆                  ┆                  ┆ player/66DEE19…  ┆           ┆                  │
│ 23010849 ┆ hc | keke        ┆ keke             ┆ /league/nemelee/ ┆ 28.725307 ┆ keke             │
│          ┆                  ┆                  ┆ player/ACFD51E…  ┆           ┆                  │
│ 23008069 ┆ Qwerty           ┆ Qwerty           ┆ /league/nemelee/ ┆ 28.154013 ┆ Qwerty           │
│          ┆                  ┆                  ┆ player/19B79D7…  ┆           ┆                  │
│ 23010981 ┆ Bigs             ┆ Bigs             ┆ /league/nemelee/ ┆ 27.883786 ┆ Bigs             │
│          ┆                  ┆                  ┆ player/06AECF7…  ┆           ┆                  │
│ 23010043 ┆ hc | Jeep God    ┆ Jeep God         ┆ /league/nemelee/ ┆ 27.432212 ┆ Jeep God         │
│          ┆                  ┆                  ┆ player/4990C91…  ┆           ┆                  │
│ 23008488 ┆ Frootbat         ┆ Frootbat         ┆ /league/nemelee/ ┆ 27.334145 ┆ Frootbat         │
│          ┆                  ┆                  ┆ player/CA6CC8E…  ┆           ┆                  │
│ 23010976 ┆ MOOP             ┆ MOOP             ┆ /league/nemelee/ ┆ 27.068878 ┆ MOOP             │
│          ┆                  ┆                  ┆ player/76E2BBC…  ┆           ┆                  │
│ 23008232 ┆ fng | InDaHouse  ┆ InDaHouse        ┆ /league/nemelee/ ┆ 26.741727 ┆ InDaHouse        │
│          ┆                  ┆                  ┆ player/C268E2A…  ┆           ┆                  │
│ 23007357 ┆ hc | Babs        ┆ Babs             ┆ /league/nemelee/ ┆ 26.626799 ┆ Babs             │
│          ┆                  ┆                  ┆ player/03D1DA3…  ┆           ┆                  │
│ 23008529 ┆ Byrne            ┆ Byrne            ┆ /league/nemelee/ ┆ 25.64798  ┆ Byrne            │
│          ┆                  ┆                  ┆ player/9F8AD0D…  ┆           ┆                  │
│ 23009701 ┆ sfy | sfy bees   ┆ sfy bees         ┆ /league/nemelee/ ┆ 23.52655  ┆ sfy bees         │
│          ┆                  ┆                  ┆ player/8434066…  ┆           ┆                  │
│ 22998770 ┆ Brotherhood |    ┆ Duffy            ┆ /league/nemelee/ ┆ 22.901703 ┆ Duffy            │
│          ┆ Duffy            ┆                  ┆ player/806202F…  ┆           ┆                  │
│ 23008797 ┆ Cheezboom        ┆ Cheezboom        ┆ /league/nemelee/ ┆ 22.781331 ┆ Cheezboom        │
│          ┆                  ┆                  ┆ player/5A137D1…  ┆           ┆                  │
│ 23008995 ┆ KBK | ren        ┆ ren              ┆ /league/nemelee/ ┆ 22.682883 ┆ ren              │
│          ┆                  ┆                  ┆ player/D2247C7…  ┆           ┆                  │
│ 23007345 ┆ GuitarLord       ┆ GuitarLord       ┆ /league/nemelee/ ┆ 19.988711 ┆ GuitarLord       │
│          ┆                  ┆                  ┆ player/C9776F7…  ┆           ┆                  │
│ 23004324 ┆ melee.boston |   ┆ Puunk_           ┆ /league/nemelee/ ┆ 19.577446 ┆ Puunk_           │
│          ┆ Puunk_           ┆                  ┆ player/2F45039…  ┆           ┆                  │
│ 23010442 ┆ RhodeIslandBean  ┆ RhodeIslandBean  ┆ /league/nemelee/ ┆ 18.238052 ┆ RhodeIslandBean  │
│          ┆                  ┆                  ┆ player/B8B5B5D…  ┆           ┆                  │
│ 23010558 ┆ hc | PajamaPal   ┆ PajamaPal        ┆ /league/nemelee/ ┆ 15.797566 ┆ PajamaPal        │
│          ┆                  ┆                  ┆ player/DE1D2B0…  ┆           ┆                  │
│ 23008421 ┆ Robert           ┆ Robert           ┆ /league/nemelee/ ┆ 14.353469 ┆ Robert           │
│          ┆ WIlliwinkle III  ┆ WIlliwinkle III  ┆ player/E65EF74…  ┆           ┆ WIlliwinkle III  │
│ 23007299 ┆ CrucialCrazy     ┆ CrucialCrazy     ┆ /league/nemelee/ ┆ 13.818493 ┆ CrucialCrazy     │
│          ┆                  ┆                  ┆ player/F511B11…  ┆           ┆                  │
│ 23009376 ┆ joe chemo        ┆ joe chemo        ┆ /league/nemelee/ ┆ 13.814782 ┆ joe chemo        │
│          ┆                  ┆                  ┆ player/8955A59…  ┆           ┆                  │
│ 23010836 ┆ RoccoChief       ┆ RoccoChief       ┆ /league/nemelee/ ┆ 13.711473 ┆ RoccoChief       │
│          ┆                  ┆                  ┆ player/4E82626…  ┆           ┆                  │
│ 23008168 ┆ Exarch           ┆ Exarch           ┆ /league/nemelee/ ┆ 12.990022 ┆ Exarch           │
│          ┆                  ┆                  ┆ player/BD62470…  ┆           ┆                  │
│ 23007181 ┆ Groggy           ┆ Groggy           ┆ /league/nemelee/ ┆ 10.853132 ┆ Groggy           │
│          ┆                  ┆                  ┆ player/B3CECD7…  ┆           ┆                  │
│ 23010623 ┆ heylayow         ┆ heylayow         ┆ /league/nemelee/ ┆ 10.699654 ┆ heylayow         │
│          ┆                  ┆                  ┆ player/6A72E56…  ┆           ┆                  │
│ 23008550 ┆ q | Coffee       ┆ Coffee           ┆ /league/nemelee/ ┆ 10.039763 ┆ Coffee           │
│          ┆                  ┆                  ┆ player/398719D…  ┆           ┆                  │
│ 23006760 ┆ BoratNorad       ┆ BoratNorad       ┆ /league/nemelee/ ┆ 8.813481  ┆ BoratNorad       │
│          ┆                  ┆                  ┆ player/90CD56B…  ┆           ┆                  │
│ 23010630 ┆ DrillYouu        ┆ DrillYouu        ┆ /league/nemelee/ ┆ 8.396699  ┆ DrillYouu        │
│          ┆                  ┆                  ┆ player/35744BA…  ┆           ┆                  │
│ 23008078 ┆ Smokin' That     ┆ Smokin' That     ┆ /league/nemelee/ ┆ 8.19618   ┆ Smokin' That     │
│          ┆ Shit!            ┆ Shit!            ┆ player/751FC75…  ┆           ┆ Shit!            │
│ 23009223 ┆ Uncle Fraski     ┆ Uncle Fraski     ┆ /league/nemelee/ ┆ 6.078272  ┆ Uncle Fraski     │
│          ┆                  ┆                  ┆ player/CEF9C72…  ┆           ┆                  │
└──────────┴──────────────────┴──────────────────┴──────────────────┴───────────┴──────────────────┘

In [26]:
entrant_seeding = (
    entrant_ratings
    .sort('rating', descending=True)
    .with_row_index('seed_num')
    .with_columns(pl.col('seed_num') + 1)
)
entrant_seeding

shape: (36, 7)
┌──────────┬──────────┬────────────────┬───────────────┬───────────────┬───────────┬───────────────┐
│ seed_num ┆ id       ┆ name           ┆ gamertag      ┆ url           ┆ rating    ┆ tag           │
│ ---      ┆ ---      ┆ ---            ┆ ---           ┆ ---           ┆ ---       ┆ ---           │
│ u32      ┆ i64      ┆ str            ┆ str           ┆ str           ┆ f64       ┆ str           │
╞══════════╪══════════╪════════════════╪═══════════════╪═══════════════╪═══════════╪═══════════════╡
│ 1        ┆ 23008215 ┆ TSI | coffee   ┆ coffee        ┆ /league/nemel ┆ 40.230426 ┆ coffee        │
│          ┆          ┆                ┆               ┆ ee/player/254 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 79C6…         ┆           ┆               │
│ 2        ┆ 23009063 ┆ Ant            ┆ Ant           ┆ /league/nemel ┆ 34.396759 ┆ Ant           │
│          ┆          ┆                ┆               ┆ ee/player/5DB ┆           ┆               │
│          ┆          ┆                ┆               ┆ CC34…         ┆           ┆               │
│ 3        ┆ 23010778 ┆ hc | Good1ife  ┆ Good1ife      ┆ /league/nemel ┆ 32.577395 ┆ Good1ife      │
│          ┆          ┆                ┆               ┆ ee/player/396 ┆           ┆               │
│          ┆          ┆                ┆               ┆ A6F1…         ┆           ┆               │
│ 4        ┆ 23008184 ┆ BRamZ          ┆ BRamZ         ┆ /league/nemel ┆ 30.096264 ┆ BRamZ         │
│          ┆          ┆                ┆               ┆ ee/player/8CB ┆           ┆               │
│          ┆          ┆                ┆               ┆ 30ED…         ┆           ┆               │
│ 5        ┆ 23009323 ┆ BonkCushy      ┆ BonkCushy     ┆ /league/nemel ┆ 29.72562  ┆ BonkCushy     │
│          ┆          ┆                ┆               ┆ ee/player/105 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 6255…         ┆           ┆               │
│ 6        ┆ 23009673 ┆ Motobug        ┆ Motobug       ┆ /league/nemel ┆ 29.643181 ┆ Motobug       │
│          ┆          ┆                ┆               ┆ ee/player/E12 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 030B…         ┆           ┆               │
│ 7        ┆ 22991834 ┆ zaubermaus     ┆ zaubermaus    ┆ /league/nemel ┆ 28.995816 ┆ zaubermaus    │
│          ┆          ┆                ┆               ┆ ee/player/66D ┆           ┆               │
│          ┆          ┆                ┆               ┆ EE19…         ┆           ┆               │
│ 8        ┆ 23010849 ┆ hc | keke      ┆ keke          ┆ /league/nemel ┆ 28.725307 ┆ keke          │
│          ┆          ┆                ┆               ┆ ee/player/ACF ┆           ┆               │
│          ┆          ┆                ┆               ┆ D51E…         ┆           ┆               │
│ 9        ┆ 23008069 ┆ Qwerty         ┆ Qwerty        ┆ /league/nemel ┆ 28.154013 ┆ Qwerty        │
│          ┆          ┆                ┆               ┆ ee/player/19B ┆           ┆               │
│          ┆          ┆                ┆               ┆ 79D7…         ┆           ┆               │
│ 10       ┆ 23010981 ┆ Bigs           ┆ Bigs          ┆ /league/nemel ┆ 27.883786 ┆ Bigs          │
│          ┆          ┆                ┆               ┆ ee/player/06A ┆           ┆               │
│          ┆          ┆                ┆               ┆ ECF7…         ┆           ┆               │
│ 11       ┆ 23010043 ┆ hc | Jeep God  ┆ Jeep God      ┆ /league/nemel ┆ 27.432212 ┆ Jeep God      │
│          ┆          ┆                ┆               ┆ ee/player/499 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 0C91…         ┆           ┆               │
│ 12       ┆ 23008488 ┆ Frootbat       ┆ Frootbat      ┆ /league/nemel ┆ 27.334145 ┆ Frootbat      │
│          ┆          ┆                ┆               ┆ ee/player/CA6 ┆           ┆               │
│          ┆          ┆                ┆               ┆ CC8E…         ┆           ┆               │
│ 13       ┆ 23010976 ┆ MOOP           ┆ MOOP          ┆ /league/nemel ┆ 27.068878 ┆ MOOP          │
│          ┆          ┆                ┆               ┆ ee/player/76E ┆           ┆               │
│          ┆          ┆                ┆               ┆ 2BBC…         ┆           ┆               │
│ 14       ┆ 23008232 ┆ fng |          ┆ InDaHouse     ┆ /league/nemel ┆ 26.741727 ┆ InDaHouse     │
│          ┆          ┆ InDaHouse      ┆               ┆ ee/player/C26 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 8E2A…         ┆           ┆               │
│ 15       ┆ 23007357 ┆ hc | Babs      ┆ Babs          ┆ /league/nemel ┆ 26.626799 ┆ Babs          │
│          ┆          ┆                ┆               ┆ ee/player/03D ┆           ┆               │
│          ┆          ┆                ┆               ┆ 1DA3…         ┆           ┆               │
│ 16       ┆ 23008529 ┆ Byrne          ┆ Byrne         ┆ /league/nemel ┆ 25.64798  ┆ Byrne         │
│          ┆          ┆                ┆               ┆ ee/player/9F8 ┆           ┆               │
│          ┆          ┆                ┆               ┆ AD0D…         ┆           ┆               │
│ 17       ┆ 23009701 ┆ sfy | sfy bees ┆ sfy bees      ┆ /league/nemel ┆ 23.52655  ┆ sfy bees      │
│          ┆          ┆                ┆               ┆ ee/player/843 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 4066…         ┆           ┆               │
│ 18       ┆ 22998770 ┆ Brotherhood |  ┆ Duffy         ┆ /league/nemel ┆ 22.901703 ┆ Duffy         │
│          ┆          ┆ Duffy          ┆               ┆ ee/player/806 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 202F…         ┆           ┆               │
│ 19       ┆ 23008797 ┆ Cheezboom      ┆ Cheezboom     ┆ /league/nemel ┆ 22.781331 ┆ Cheezboom     │
│          ┆          ┆                ┆               ┆ ee/player/5A1 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 37D1…         ┆           ┆               │
│ 20       ┆ 23008995 ┆ KBK | ren      ┆ ren           ┆ /league/nemel ┆ 22.682883 ┆ ren           │
│          ┆          ┆                ┆               ┆ ee/player/D22 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 47C7…         ┆           ┆               │
│ 21       ┆ 23007345 ┆ GuitarLord     ┆ GuitarLord    ┆ /league/nemel ┆ 19.988711 ┆ GuitarLord    │
│          ┆          ┆                ┆               ┆ ee/player/C97 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 76F7…         ┆           ┆               │
│ 22       ┆ 23004324 ┆ melee.boston | ┆ Puunk_        ┆ /league/nemel ┆ 19.577446 ┆ Puunk_        │
│          ┆          ┆ Puunk_         ┆               ┆ ee/player/2F4 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 5039…         ┆           ┆               │
│ 23       ┆ 23010442 ┆ RhodeIslandBea ┆ RhodeIslandBe ┆ /league/nemel ┆ 18.238052 ┆ RhodeIslandBe │
│          ┆          ┆ n              ┆ an            ┆ ee/player/B8B ┆           ┆ an            │
│          ┆          ┆                ┆               ┆ 5B5D…         ┆           ┆               │
│ 24       ┆ 23010558 ┆ hc | PajamaPal ┆ PajamaPal     ┆ /league/nemel ┆ 15.797566 ┆ PajamaPal     │
│          ┆          ┆                ┆               ┆ ee/player/DE1 ┆           ┆               │
│          ┆          ┆                ┆               ┆ D2B0…         ┆           ┆               │
│ 25       ┆ 23008421 ┆ Robert         ┆ Robert        ┆ /league/nemel ┆ 14.353469 ┆ Robert        │
│          ┆          ┆ WIlliwinkle    ┆ WIlliwinkle   ┆ ee/player/E65 ┆           ┆ WIlliwinkle   │
│          ┆          ┆ III            ┆ III           ┆ EF74…         ┆           ┆ III           │
│ 26       ┆ 23007299 ┆ CrucialCrazy   ┆ CrucialCrazy  ┆ /league/nemel ┆ 13.818493 ┆ CrucialCrazy  │
│          ┆          ┆                ┆               ┆ ee/player/F51 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 1B11…         ┆           ┆               │
│ 27       ┆ 23009376 ┆ joe chemo      ┆ joe chemo     ┆ /league/nemel ┆ 13.814782 ┆ joe chemo     │
│          ┆          ┆                ┆               ┆ ee/player/895 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 5A59…         ┆           ┆               │
│ 28       ┆ 23010836 ┆ RoccoChief     ┆ RoccoChief    ┆ /league/nemel ┆ 13.711473 ┆ RoccoChief    │
│          ┆          ┆                ┆               ┆ ee/player/4E8 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 2626…         ┆           ┆               │
│ 29       ┆ 23008168 ┆ Exarch         ┆ Exarch        ┆ /league/nemel ┆ 12.990022 ┆ Exarch        │
│          ┆          ┆                ┆               ┆ ee/player/BD6 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 2470…         ┆           ┆               │
│ 30       ┆ 23007181 ┆ Groggy         ┆ Groggy        ┆ /league/nemel ┆ 10.853132 ┆ Groggy        │
│          ┆          ┆                ┆               ┆ ee/player/B3C ┆           ┆               │
│          ┆          ┆                ┆               ┆ ECD7…         ┆           ┆               │
│ 31       ┆ 23010623 ┆ heylayow       ┆ heylayow      ┆ /league/nemel ┆ 10.699654 ┆ heylayow      │
│          ┆          ┆                ┆               ┆ ee/player/6A7 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 2E56…         ┆           ┆               │
│ 32       ┆ 23008550 ┆ q | Coffee     ┆ Coffee        ┆ /league/nemel ┆ 10.039763 ┆ Coffee        │
│          ┆          ┆                ┆               ┆ ee/player/398 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 719D…         ┆           ┆               │
│ 33       ┆ 23006760 ┆ BoratNorad     ┆ BoratNorad    ┆ /league/nemel ┆ 8.813481  ┆ BoratNorad    │
│          ┆          ┆                ┆               ┆ ee/player/90C ┆           ┆               │
│          ┆          ┆                ┆               ┆ D56B…         ┆           ┆               │
│ 34       ┆ 23010630 ┆ DrillYouu      ┆ DrillYouu     ┆ /league/nemel ┆ 8.396699  ┆ DrillYouu     │
│          ┆          ┆                ┆               ┆ ee/player/357 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 44BA…         ┆           ┆               │
│ 35       ┆ 23008078 ┆ Smokin' That   ┆ Smokin' That  ┆ /league/nemel ┆ 8.19618   ┆ Smokin' That  │
│          ┆          ┆ Shit!          ┆ Shit!         ┆ ee/player/751 ┆           ┆ Shit!         │
│          ┆          ┆                ┆               ┆ FC75…         ┆           ┆               │
│ 36       ┆ 23009223 ┆ Uncle Fraski   ┆ Uncle Fraski  ┆ /league/nemel ┆ 6.078272  ┆ Uncle Fraski  │
│          ┆          ┆                ┆               ┆ ee/player/CEF ┆           ┆               │
│          ┆          ┆                ┆               ┆ 9C72…         ┆           ┆               │
└──────────┴──────────┴────────────────┴───────────────┴───────────────┴───────────┴───────────────┘

# Optimize seeding to avoid repeat matchups
Swaps similarly-rated players within tiers to separate frequent opponents in the bracket.
Recency-weighted: recent matchups penalized more (90-day half-life by default).

In [27]:
from seeding_utils import build_matchup_matrix, optimize_seeding, format_swap_report

matches = pl.read_csv('data/matches.csv')

# Build recency-weighted matchup matrix for entrants
entrant_urls = entrant_seeding.filter(pl.col('url').is_not_null()).select('url').to_series().to_list()
matchup_matrix = build_matchup_matrix(matches, entrant_urls, half_life_days=90)

print(f"Matchup pairs found: {len(matchup_matrix)}")

# Show top-10 most frequent pairings among entrants
top_matchups = sorted(matchup_matrix.items(), key=lambda x: -x[1])[:20]
url_to_tag = dict(zip(
    entrant_seeding.select('url').to_series().to_list(),
    entrant_seeding.select('gamertag').to_series().to_list()
))
print("\nTop matchups among entrants:")
for (a, b), w in top_matchups:
    print(f"  {url_to_tag.get(a, a)} vs {url_to_tag.get(b, b)}: {w:.2f}")

Matchup pairs found: 241

Top matchups among entrants:
  Qwerty vs Frootbat: 3.17
  BonkCushy vs Qwerty: 3.06
  Babs vs ren: 3.03
  Ant vs zaubermaus: 2.63
  RhodeIslandBean vs Exarch: 2.61
  Byrne vs ren: 2.59
  Jeep God vs Cheezboom: 2.51
  BonkCushy vs keke: 2.40
  Byrne vs Frootbat: 2.40
  Cheezboom vs keke: 2.35
  zaubermaus vs Byrne: 2.30
  zaubermaus vs keke: 2.22
  Good1ife vs Jeep God: 2.15
  Cheezboom vs Exarch: 2.13
  Babs vs Byrne: 2.12
  Duffy vs ren: 2.06
  Qwerty vs Duffy: 2.03
  Jeep God vs zaubermaus: 2.01
  coffee vs BRamZ: 1.95
  BonkCushy vs zaubermaus: 1.93

In [28]:
# Run the optimizer
optimized_seeding, swaps, final_cost = optimize_seeding(
    entrant_seeding,
    matchup_matrix,
    url_col='url',
    seed_col='seed_num',
    max_seed_distance=6,
)

# Show swap summary
print(format_swap_report(swaps, entrant_seeding, url_col='url', tag_col='gamertag'))
print(f"\nFinal cost: {final_cost:.2f}")

Swaps made: 24
  Seed 3 ↔ 4: BRamZ ↔ Good1ife (cost −1.66)
  Seed 5 ↔ 6: Motobug ↔ BonkCushy (cost −2.56)
  Seed 7 ↔ 8: keke ↔ zaubermaus (cost −1.08)
  Seed 9 ↔ 10: Bigs ↔ Qwerty (cost −3.25)
  Seed 9 ↔ 12: Frootbat ↔ Bigs (cost −3.76)
  Seed 11 ↔ 15: Babs ↔ Jeep God (cost −1.32)
  Seed 15 ↔ 16: Byrne ↔ Jeep God (cost −3.25)
  Seed 17 ↔ 18: Duffy ↔ sfy bees (cost −0.99)
  Seed 17 ↔ 22: Puunk_ ↔ Duffy (cost −1.10)
  Seed 18 ↔ 22: Duffy ↔ sfy bees (cost −0.08)
  Seed 20 ↔ 21: GuitarLord ↔ ren (cost −2.28)
  Seed 20 ↔ 22: sfy bees ↔ GuitarLord (cost −0.57)
  Seed 23 ↔ 29: Exarch ↔ RhodeIslandBean (cost −0.49)
  Seed 24 ↔ 25: Robert WIlliwinkle III ↔ PajamaPal (cost −0.15)
  Seed 26 ↔ 32: Coffee ↔ CrucialCrazy (cost −4.67)
  Seed 27 ↔ 29: RhodeIslandBean ↔ joe chemo (cost −0.20)
  Seed 5 ↔ 7: keke ↔ Motobug (cost −0.18)
  Seed 9 ↔ 10: Qwerty ↔ Frootbat (cost −5.14)
  Seed 24 ↔ 27: RhodeIslandBean ↔ Robert WIlliwinkle III (cost −0.00)
  Seed 25 ↔ 27: Robert WIlliwinkle III ↔ PajamaPal (cost −0.76)
  Seed 28 ↔ 29: joe chemo ↔ RoccoChief (cost −1.72)
  Seed 29 ↔ 31: heylayow ↔ RoccoChief (cost −0.07)
  Seed 24 ↔ 25: Robert WIlliwinkle III ↔ RhodeIslandBean (cost −0.00)
  Seed 27 ↔ 29: heylayow ↔ PajamaPal (cost −0.17)

Final cost: 238.61

In [29]:
# Show before/after comparison for changed seeds
changed = (
    optimized_seeding
    .filter(pl.col('seed_num') != pl.col('original_seed'))
    .select('gamertag', 'original_seed', 'seed_num', 'rating')
)
print(f"Seeds changed: {changed.height} / {entrant_seeding.height}")
changed

Seeds changed: 24 / 36

shape: (24, 4)
┌────────────────────────┬───────────────┬──────────┬───────────┐
│ gamertag               ┆ original_seed ┆ seed_num ┆ rating    │
│ ---                    ┆ ---           ┆ ---      ┆ ---       │
│ str                    ┆ u32           ┆ i64      ┆ f64       │
╞════════════════════════╪═══════════════╪══════════╪═══════════╡
│ BRamZ                  ┆ 4             ┆ 3        ┆ 30.096264 │
│ Good1ife               ┆ 3             ┆ 4        ┆ 32.577395 │
│ keke                   ┆ 8             ┆ 5        ┆ 28.725307 │
│ BonkCushy              ┆ 5             ┆ 6        ┆ 29.72562  │
│ Motobug                ┆ 6             ┆ 7        ┆ 29.643181 │
│ zaubermaus             ┆ 7             ┆ 8        ┆ 28.995816 │
│ Frootbat               ┆ 12            ┆ 10       ┆ 27.334145 │
│ Babs                   ┆ 15            ┆ 11       ┆ 26.626799 │
│ Bigs                   ┆ 10            ┆ 12       ┆ 27.883786 │
│ Byrne                  ┆ 16            ┆ 15       ┆ 25.64798  │
│ Jeep God               ┆ 11            ┆ 16       ┆ 27.432212 │
│ Puunk_                 ┆ 22            ┆ 17       ┆ 19.577446 │
│ sfy bees               ┆ 17            ┆ 20       ┆ 23.52655  │
│ ren                    ┆ 20            ┆ 21       ┆ 22.682883 │
│ GuitarLord             ┆ 21            ┆ 22       ┆ 19.988711 │
│ Exarch                 ┆ 29            ┆ 23       ┆ 12.990022 │
│ Robert WIlliwinkle III ┆ 25            ┆ 24       ┆ 14.353469 │
│ RhodeIslandBean        ┆ 23            ┆ 25       ┆ 18.238052 │
│ Coffee                 ┆ 32            ┆ 26       ┆ 10.039763 │
│ heylayow               ┆ 31            ┆ 27       ┆ 10.699654 │
│ joe chemo              ┆ 27            ┆ 28       ┆ 13.814782 │
│ PajamaPal              ┆ 24            ┆ 29       ┆ 15.797566 │
│ RoccoChief             ┆ 28            ┆ 31       ┆ 13.711473 │
│ CrucialCrazy           ┆ 26            ┆ 32       ┆ 13.818493 │
└────────────────────────┴───────────────┴──────────┴───────────┘

In [30]:
# Use optimized seeding for export (replaces entrant_seeding downstream)
entrant_seeding = optimized_seeding
entrant_seeding

shape: (36, 8)
┌──────────┬──────────┬────────────┬────────────┬────────────┬───────────┬────────────┬────────────┐
│ seed_num ┆ id       ┆ name       ┆ gamertag   ┆ url        ┆ rating    ┆ tag        ┆ original_s │
│ ---      ┆ ---      ┆ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---        ┆ eed        │
│ i64      ┆ i64      ┆ str        ┆ str        ┆ str        ┆ f64       ┆ str        ┆ ---        │
│          ┆          ┆            ┆            ┆            ┆           ┆            ┆ u32        │
╞══════════╪══════════╪════════════╪════════════╪════════════╪═══════════╪════════════╪════════════╡
│ 1        ┆ 23008215 ┆ TSI |      ┆ coffee     ┆ /league/ne ┆ 40.230426 ┆ coffee     ┆ 1          │
│          ┆          ┆ coffee     ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/25479C6 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 2        ┆ 23009063 ┆ Ant        ┆ Ant        ┆ /league/ne ┆ 34.396759 ┆ Ant        ┆ 2          │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/5DBCC34 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 3        ┆ 23008184 ┆ BRamZ      ┆ BRamZ      ┆ /league/ne ┆ 30.096264 ┆ BRamZ      ┆ 4          │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/8CB30ED ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 4        ┆ 23010778 ┆ hc |       ┆ Good1ife   ┆ /league/ne ┆ 32.577395 ┆ Good1ife   ┆ 3          │
│          ┆          ┆ Good1ife   ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/396A6F1 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 5        ┆ 23010849 ┆ hc | keke  ┆ keke       ┆ /league/ne ┆ 28.725307 ┆ keke       ┆ 8          │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/ACFD51E ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 6        ┆ 23009323 ┆ BonkCushy  ┆ BonkCushy  ┆ /league/ne ┆ 29.72562  ┆ BonkCushy  ┆ 5          │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/1056255 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 7        ┆ 23009673 ┆ Motobug    ┆ Motobug    ┆ /league/ne ┆ 29.643181 ┆ Motobug    ┆ 6          │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/E12030B ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 8        ┆ 22991834 ┆ zaubermaus ┆ zaubermaus ┆ /league/ne ┆ 28.995816 ┆ zaubermaus ┆ 7          │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/66DEE19 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 9        ┆ 23008069 ┆ Qwerty     ┆ Qwerty     ┆ /league/ne ┆ 28.154013 ┆ Qwerty     ┆ 9          │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/19B79D7 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 10       ┆ 23008488 ┆ Frootbat   ┆ Frootbat   ┆ /league/ne ┆ 27.334145 ┆ Frootbat   ┆ 12         │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/CA6CC8E ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 11       ┆ 23007357 ┆ hc | Babs  ┆ Babs       ┆ /league/ne ┆ 26.626799 ┆ Babs       ┆ 15         │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/03D1DA3 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 12       ┆ 23010981 ┆ Bigs       ┆ Bigs       ┆ /league/ne ┆ 27.883786 ┆ Bigs       ┆ 10         │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/06AECF7 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 13       ┆ 23010976 ┆ MOOP       ┆ MOOP       ┆ /league/ne ┆ 27.068878 ┆ MOOP       ┆ 13         │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/76E2BBC ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 14       ┆ 23008232 ┆ fng |      ┆ InDaHouse  ┆ /league/ne ┆ 26.741727 ┆ InDaHouse  ┆ 14         │
│          ┆          ┆ InDaHouse  ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/C268E2A ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 15       ┆ 23008529 ┆ Byrne      ┆ Byrne      ┆ /league/ne ┆ 25.64798  ┆ Byrne      ┆ 16         │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/9F8AD0D ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 16       ┆ 23010043 ┆ hc | Jeep  ┆ Jeep God   ┆ /league/ne ┆ 27.432212 ┆ Jeep God   ┆ 11         │
│          ┆          ┆ God        ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/4990C91 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 17       ┆ 23004324 ┆ melee.bost ┆ Puunk_     ┆ /league/ne ┆ 19.577446 ┆ Puunk_     ┆ 22         │
│          ┆          ┆ on |       ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆ Puunk_     ┆            ┆ er/2F45039 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 18       ┆ 22998770 ┆ Brotherhoo ┆ Duffy      ┆ /league/ne ┆ 22.901703 ┆ Duffy      ┆ 18         │
│          ┆          ┆ d | Duffy  ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/806202F ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 19       ┆ 23008797 ┆ Cheezboom  ┆ Cheezboom  ┆ /league/ne ┆ 22.781331 ┆ Cheezboom  ┆ 19         │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/5A137D1 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 20       ┆ 23009701 ┆ sfy | sfy  ┆ sfy bees   ┆ /league/ne ┆ 23.52655  ┆ sfy bees   ┆ 17         │
│          ┆          ┆ bees       ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/8434066 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 21       ┆ 23008995 ┆ KBK | ren  ┆ ren        ┆ /league/ne ┆ 22.682883 ┆ ren        ┆ 20         │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/D2247C7 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 22       ┆ 23007345 ┆ GuitarLord ┆ GuitarLord ┆ /league/ne ┆ 19.988711 ┆ GuitarLord ┆ 21         │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/C9776F7 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 23       ┆ 23008168 ┆ Exarch     ┆ Exarch     ┆ /league/ne ┆ 12.990022 ┆ Exarch     ┆ 29         │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/BD62470 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 24       ┆ 23008421 ┆ Robert WIl ┆ Robert WIl ┆ /league/ne ┆ 14.353469 ┆ Robert WIl ┆ 25         │
│          ┆          ┆ liwinkle   ┆ liwinkle   ┆ melee/play ┆           ┆ liwinkle   ┆            │
│          ┆          ┆ III        ┆ III        ┆ er/E65EF74 ┆           ┆ III        ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 25       ┆ 23010442 ┆ RhodeIslan ┆ RhodeIslan ┆ /league/ne ┆ 18.238052 ┆ RhodeIslan ┆ 23         │
│          ┆          ┆ dBean      ┆ dBean      ┆ melee/play ┆           ┆ dBean      ┆            │
│          ┆          ┆            ┆            ┆ er/B8B5B5D ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 26       ┆ 23008550 ┆ q | Coffee ┆ Coffee     ┆ /league/ne ┆ 10.039763 ┆ Coffee     ┆ 32         │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/398719D ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 27       ┆ 23010623 ┆ heylayow   ┆ heylayow   ┆ /league/ne ┆ 10.699654 ┆ heylayow   ┆ 31         │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/6A72E56 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 28       ┆ 23009376 ┆ joe chemo  ┆ joe chemo  ┆ /league/ne ┆ 13.814782 ┆ joe chemo  ┆ 27         │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/8955A59 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 29       ┆ 23010558 ┆ hc |       ┆ PajamaPal  ┆ /league/ne ┆ 15.797566 ┆ PajamaPal  ┆ 24         │
│          ┆          ┆ PajamaPal  ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/DE1D2B0 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 30       ┆ 23007181 ┆ Groggy     ┆ Groggy     ┆ /league/ne ┆ 10.853132 ┆ Groggy     ┆ 30         │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/B3CECD7 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 31       ┆ 23010836 ┆ RoccoChief ┆ RoccoChief ┆ /league/ne ┆ 13.711473 ┆ RoccoChief ┆ 28         │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/4E82626 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 32       ┆ 23007299 ┆ CrucialCra ┆ CrucialCra ┆ /league/ne ┆ 13.818493 ┆ CrucialCra ┆ 26         │
│          ┆          ┆ zy         ┆ zy         ┆ melee/play ┆           ┆ zy         ┆            │
│          ┆          ┆            ┆            ┆ er/F511B11 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 33       ┆ 23006760 ┆ BoratNorad ┆ BoratNorad ┆ /league/ne ┆ 8.813481  ┆ BoratNorad ┆ 33         │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/90CD56B ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 34       ┆ 23010630 ┆ DrillYouu  ┆ DrillYouu  ┆ /league/ne ┆ 8.396699  ┆ DrillYouu  ┆ 34         │
│          ┆          ┆            ┆            ┆ melee/play ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ er/35744BA ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 35       ┆ 23008078 ┆ Smokin'    ┆ Smokin'    ┆ /league/ne ┆ 8.19618   ┆ Smokin'    ┆ 35         │
│          ┆          ┆ That Shit! ┆ That Shit! ┆ melee/play ┆           ┆ That Shit! ┆            │
│          ┆          ┆            ┆            ┆ er/751FC75 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
│ 36       ┆ 23009223 ┆ Uncle      ┆ Uncle      ┆ /league/ne ┆ 6.078272  ┆ Uncle      ┆ 36         │
│          ┆          ┆ Fraski     ┆ Fraski     ┆ melee/play ┆           ┆ Fraski     ┆            │
│          ┆          ┆            ┆            ┆ er/CEF9C72 ┆           ┆            ┆            │
│          ┆          ┆            ┆            ┆ …          ┆           ┆            ┆            │
└──────────┴──────────┴────────────┴────────────┴────────────┴───────────┴────────────┴────────────┘

# Export seeding to start gg

In [56]:
# Query to get phase IDs for Melee Singles event
phases_query = gql("""
query EventPhases($eventId: ID!) {
    event(id: $eventId) {
        phases {
            id
            name
            numSeeds
        }
    }
}
""")

phases_variables = {"eventId": melee_singles_id}

try:
        phases_result = client.execute(phases_query, variable_values=phases_variables)
        print(json.dumps(phases_result, indent=2))
except Exception as e:
        print("Error fetching phases:", e)

phase_id = phases_result['event']['phases'][0]['id']
print(f'phase id: {phase_id}')

{
  "event": {
    "phases": [
      {
        "id": 2231455,
        "name": "Bracket",
        "numSeeds": 34
      }
    ]
  }
}
phase id: 2231455

In [57]:
# ...existing code...

# 1. Fetch seeds for the phase
seeds_query = gql("""
query PhaseSeeds($phaseId: ID!) {
  phase(id: $phaseId) {
    seeds(query: {perPage: 512}) {
      nodes {
        id
        entrant {
          id
        }
      }
    }
  }
}
""")
seeds_result = client.execute(seeds_query, variable_values={"phaseId": phase_id})
seed_nodes = seeds_result["phase"]["seeds"]["nodes"]
entrantid_to_seedid = {seed["entrant"]["id"]: seed["id"] for seed in seed_nodes}

# 2. Prepare seed mapping using correct seedId
seed_mapping = []
for row in entrant_seeding.iter_rows(named=True):
    entrant_id = int(row["id"])
    seed_id = entrantid_to_seedid.get(entrant_id)
    if seed_id:
        seed_mapping.append({
            "seedId": seed_id,
            "seedNum": row["seed_num"],
        })
    else:
        print(f"Warning: No seed found for entrant {entrant_id}")

print(f"Importing {len(seed_mapping)} seeds to phase {phase_id}...")

Importing 34 seeds to phase 2231455...

In [58]:
entrant_seeding = (
    entrant_seeding
    .with_columns(pl.col('id').map_elements(lambda x: entrantid_to_seedid.get(x, None)).alias('seed_id'))
)

/tmp/ipykernel_39283/1705157941.py:3: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
  .with_columns(pl.col('id').map_elements(lambda x: entrantid_to_seedid.get(x, None)).alias('seed_id'))

In [59]:
(
    player_ratings
    .select(pl.col('tag'))
)

shape: (2_515, 1)
┌─────────────────────────────────┐
│ tag                             │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ Nouns | Aklo                    │
│ DTL | 2Saint                    │
│ RedBull GG IFM | aMSa           │
│ Spark                           │
│ SDJ                             │
│ FLY | Jmook                     │
│ MATE | Kalvar                   │
│ Epoodle                         │
│ S3C | RapMonster                │
│ Inky                            │
│ DrLobster                       │
│ MF | KoDoRiN                    │
│ YAMI                            │
│ SHDJ | Mekk                     │
│ TLOC | Salt                     │
│ max                             │
│ TC | Zanya                      │
│ Kacey                           │
│ 404Cray                         │
│ BLITZ | PSA | Kikoho            │
│ Goodie                          │
│ PBI | Bekvin                    │
│ bonfire10                       │
│ Chem                            │
│ chef                            │
│ Mot$                            │
│ HPR                             │
│ Brotherhood | Foxy Grandpa      │
│ LG | Louis                      │
│ Younger                         │
│ CM| WG|  Jflex | Jflex          │
│ CLM/JPM | Skerzo                │
│ Dawson                          │
│ Bbatts                          │
│ L7 | Agent                      │
│ Bumba | Silver                  │
│ VWBG | alright                  │
│ Panda                           │
│ egg                             │
│ Thunderlight | essy             │
│ TSI | coffee                    │
│ TL | ChuDat                     │
│ Chitanda Neru                   │
│ Grab                            │
│ Melee Stats | Abbe              │
│ cupofwater                      │
│ Tommy                           │
│ frog | Zamu                     │
│ Project                         │
│ Trail                           │
│ …                               │
│ Ensign | Brak                   │
│ kennedynight                    │
│ Petry                           │
│ BoratNorad                      │
│ Harryhood05                     │
│ MatSnah                         │
│ MrFluffyNess2                   │
│ Carls100                        │
│ astrodesert                     │
│ corvo                           │
│ Roughnut29                      │
│ MAIF                            │
│ RNBW | Dorothy                  │
│ HTC | gmiller                   │
│ moonrithyll                     │
│ Olethros2504                    │
│ Feed's Friend | Monotone Culpr… │
│ c0 | routuro                    │
│ Smigulvits                      │
│ Jayne_Etho                      │
│ Macrol                          │
│ Feed                            │
│ JoeNut                          │
│ PLAID                           │
│ Uncle Fraski                    │
│ crash0ut | StarDestiny34        │
│ Lua                             │
│ N0va | Breathlessx22            │
│ CrazyJake                       │
│ SirMichael                      │
│ Kilroy                          │
│ Liquid Llama                    │
│ Mammoth                         │
│ zweeP                           │
│ ZeperTheStar                    │
│ Aeacus                          │
│ Julia                           │
│ SwankyD                         │
│ TD | U4iK                       │
│ yamir                           │
│ Liquid | Julzz                  │
│ AK Sparx                        │
│ crash0ut | Awkward.             │
│ Zeas44                          │
│ ShnooksNcookS                   │
│ Cryonova                        │
│ Skel                            │
│ eemee                           │
│ RosieCo | Pure                  │
│ IDGM                            │
└─────────────────────────────────┘

In [38]:
# Prepare seed mapping from entrant_ratings for the phase
seed_mapping = []
for row in entrant_seeding.iter_rows(named=True):
    seed_mapping.append({
        "seedId": row["seed_id"],
        "seedNum": row['seed_num'],
    })

print(f"Importing {len(seed_mapping)} seeds to phase {phase_id}...")

mutation = gql("""
mutation UpdatePhaseSeeding($phaseId: ID!, $seedMapping: [UpdatePhaseSeedInfo]!) {
  updatePhaseSeeding(phaseId: $phaseId, seedMapping: $seedMapping) {
    id
  }
}
""")

params = {
    "phaseId": phase_id,
    "seedMapping": seed_mapping,
}

try:
    result = client.execute(mutation, variable_values=params)
    print('Success!')
    print(result)
except Exception as e:
    print('Error:', e)

Importing 22 seeds to phase 2231455...
Success!
{'updatePhaseSeeding': {'id': 2231455}}

# view previous tournaments by player

In [39]:
player = 'hotdaniel'

In [40]:
from IPython.display import display, HTML

def display_side_by_side(*args, titles=('',)):
    html_str = ''
    if len(titles) > 0:
        html_str += '<div style="display:flex">'
    for df, title in zip(args, titles + ('',) * (len(args) - len(titles))):
        html_str += '<div style="margin-right:20px">'
        if title:
            html_str += f'<h2>{title}</h2>'
        html_str += df.to_html()
        html_str += '</div>'
    html_str += '</div>'
    display(HTML(html_str))

In [41]:
matches = pl.read_csv('data/matches-with-ratings.csv')

In [42]:
last_n_matches = (
    matches
    .filter(
        pl.col('winner').str.to_lowercase().str.contains(player.lower()) |
        pl.col('loser').str.to_lowercase().str.contains(player.lower())
    )
    .sort('tournament_date', 'encounter_id', descending=True)
    .head(40)
)
losses = (
    last_n_matches
    .filter(pl.col('loser').str.to_lowercase().str.contains(player.lower()))
    .select(
        pl.col('winner').alias('tag'),
        'winner_rating',
        'tournament_name',
        'tournament_date',
        'loser_score',
    )
    .sort('winner_rating', descending=False)
)
wins = (
    last_n_matches
    .filter(pl.col('winner').str.to_lowercase().str.contains(player.lower()))
    .select(
        pl.col('loser').alias('tag'),
        'loser_rating',
        'tournament_name',
        'tournament_date',
        'winner_score',
    )
    .sort('loser_rating', descending=True)
)
display_side_by_side(
    losses.to_pandas(),
    wins.to_pandas(),
    titles=('Losses', 'Wins')
)

# ELO of all attendees

In [43]:
# Use the tournament id from your earlier query
tournament_id = tournament_result['tournament']['id']

attendees_query = gql("""
query TournamentAttendees($tournamentId: ID!) {
  tournament(id: $tournamentId) {
    participants(query: {perPage: 512}) {
      nodes {
        id
        gamerTag
        user {
          id
          name
        }
      }
    }
  }
}
""")

attendees_variables = {"tournamentId": tournament_id}

try:
    attendees_result = client.execute(attendees_query, variable_values=attendees_variables)
    # Flatten and display as DataFrame
    import polars as pl
    attendee_nodes = attendees_result['tournament']['participants']['nodes']
    attendees = pl.DataFrame([
        {
            "id": a["id"],
            "gamerTag": a["gamerTag"],
            "user_id": a["user"]["id"] if a["user"] else None,
            "user_name": a["user"]["name"] if a["user"] else None,
        }
        for a in attendee_nodes
    ])
    attendees
except Exception as e:
    print("Error fetching tournament attendees:", e)

attendees

shape: (27, 4)
┌──────────┬─────────────────────┬─────────┬─────────────────┐
│ id       ┆ gamerTag            ┆ user_id ┆ user_name       │
│ ---      ┆ ---                 ┆ ---     ┆ ---             │
│ i64      ┆ str                 ┆ i64     ┆ str             │
╞══════════╪═════════════════════╪═════════╪═════════════════╡
│ 21080785 ┆ Duffy               ┆ 3166576 ┆ null            │
│ 21082190 ┆ BonkCushy           ┆ 187     ┆ Dan Cushing     │
│ 21078879 ┆ MEAT                ┆ 177939  ┆ Grant Foster    │
│ 21083157 ┆ Cheezboom           ┆ 2762869 ┆ Jared B.        │
│ 21077283 ┆ Tpoz                ┆ 1001870 ┆ Pato Mora       │
│ 21081837 ┆ sfy bees            ┆ 34163   ┆ Tyler Sherer    │
│ 21082933 ┆ Lermonz             ┆ 614035  ┆ Lena Navin      │
│ 21080263 ┆ Eol                 ┆ 3213021 ┆ null            │
│ 21076526 ┆ kwest               ┆ 106074  ┆ Karen West      │
│ 21081400 ┆ Yep                 ┆ 3313450 ┆ null            │
│ 21081868 ┆ bfu                 ┆ 2900434 ┆ null            │
│ 21082843 ┆ bonfire10           ┆ 409     ┆ Tori Paolillo   │
│ 21082964 ┆ Petotae             ┆ 985473  ┆ Peter Savinelli │
│ 21079100 ┆ Idkwhattocallmyself ┆ 3147972 ┆ null            │
│ 21083063 ┆ RoccoChief          ┆ 2426665 ┆ null            │
│ 21082199 ┆ keke                ┆ 34096   ┆ Jake Donovan    │
│ 21081599 ┆ Frootbat            ┆ 1013876 ┆ Jordan Jones    │
│ 21042727 ┆ zaubermaus          ┆ 305778  ┆ Aaron Giera     │
│ 21080350 ┆ Babs                ┆ 356016  ┆ Cameron G.      │
│ 21079813 ┆ BoratNorad          ┆ 2767955 ┆ null            │
│ 21082682 ┆ MOOP                ┆ 39824   ┆ Ryan H.         │
│ 21083122 ┆ Byrne               ┆ 2926126 ┆ null            │
│ 21071201 ┆ HotPeppers          ┆ 2074352 ┆ null            │
│ 21081947 ┆ ren                 ┆ 2792560 ┆ null            │
│ 21082393 ┆ InDaHouse           ┆ 48367   ┆ Daniel Valadas  │
│ 21081697 ┆ coffee              ┆ 548818  ┆ Alex S.         │
│ 21078708 ┆ saucymain           ┆ 668760  ┆ null            │
└──────────┴─────────────────────┴─────────┴─────────────────┘

In [44]:
# Join attendees on ratings and sort by rating (descending)
attendee_ratings = (
    attendees
    .with_columns(pl.col('gamerTag').str.to_lowercase().alias('gamertag'))
    .join(
        player_ratings.with_columns(
            pl.col('tag').str.split(' | ').list.last().str.to_lowercase()
        ),
        left_on='gamertag',
        right_on='tag',
        how='left'
    )
    .sort('rating', descending=True)
)
attendee_ratings

shape: (31, 7)
┌──────────┬────────────────┬─────────┬────────────────┬───────────────┬───────────────┬───────────┐
│ id       ┆ gamerTag       ┆ user_id ┆ user_name      ┆ gamertag      ┆ url           ┆ rating    │
│ ---      ┆ ---            ┆ ---     ┆ ---            ┆ ---           ┆ ---           ┆ ---       │
│ i64      ┆ str            ┆ i64     ┆ str            ┆ str           ┆ str           ┆ f64       │
╞══════════╪════════════════╪═════════╪════════════════╪═══════════════╪═══════════════╪═══════════╡
│ 21076526 ┆ kwest          ┆ 106074  ┆ Karen West     ┆ kwest         ┆ null          ┆ null      │
│ 21081400 ┆ Yep            ┆ 3313450 ┆ null           ┆ yep           ┆ null          ┆ null      │
│ 21082843 ┆ bonfire10      ┆ 409     ┆ Tori Paolillo  ┆ bonfire10     ┆ /league/nemel ┆ 42.254872 │
│          ┆                ┆         ┆                ┆               ┆ ee/player/C9B ┆           │
│          ┆                ┆         ┆                ┆               ┆ 8492…         ┆           │
│ 21081697 ┆ coffee         ┆ 548818  ┆ Alex S.        ┆ coffee        ┆ /league/nemel ┆ 40.337837 │
│          ┆                ┆         ┆                ┆               ┆ ee/player/254 ┆           │
│          ┆                ┆         ┆                ┆               ┆ 79C6…         ┆           │
│ 21078879 ┆ MEAT           ┆ 177939  ┆ Grant Foster   ┆ meat          ┆ /league/nemel ┆ 34.761998 │
│          ┆                ┆         ┆                ┆               ┆ ee/player/0D8 ┆           │
│          ┆                ┆         ┆                ┆               ┆ C1F3…         ┆           │
│ 21078708 ┆ saucymain      ┆ 668760  ┆ null           ┆ saucymain     ┆ /league/nemel ┆ 34.501203 │
│          ┆                ┆         ┆                ┆               ┆ ee/player/240 ┆           │
│          ┆                ┆         ┆                ┆               ┆ 7F41…         ┆           │
│ 21082190 ┆ BonkCushy      ┆ 187     ┆ Dan Cushing    ┆ bonkcushy     ┆ /league/nemel ┆ 30.466068 │
│          ┆                ┆         ┆                ┆               ┆ ee/player/105 ┆           │
│          ┆                ┆         ┆                ┆               ┆ 6255…         ┆           │
│ 21042727 ┆ zaubermaus     ┆ 305778  ┆ Aaron Giera    ┆ zaubermaus    ┆ /league/nemel ┆ 29.000814 │
│          ┆                ┆         ┆                ┆               ┆ ee/player/66D ┆           │
│          ┆                ┆         ┆                ┆               ┆ EE19…         ┆           │
│ 21082199 ┆ keke           ┆ 34096   ┆ Jake Donovan   ┆ keke          ┆ /league/nemel ┆ 28.693111 │
│          ┆                ┆         ┆                ┆               ┆ ee/player/ACF ┆           │
│          ┆                ┆         ┆                ┆               ┆ D51E…         ┆           │
│ 21081599 ┆ Frootbat       ┆ 1013876 ┆ Jordan Jones   ┆ frootbat      ┆ /league/nemel ┆ 27.600955 │
│          ┆                ┆         ┆                ┆               ┆ ee/player/CA6 ┆           │
│          ┆                ┆         ┆                ┆               ┆ CC8E…         ┆           │
│ 21082393 ┆ InDaHouse      ┆ 48367   ┆ Daniel Valadas ┆ indahouse     ┆ /league/nemel ┆ 27.305792 │
│          ┆                ┆         ┆                ┆               ┆ ee/player/C26 ┆           │
│          ┆                ┆         ┆                ┆               ┆ 8E2A…         ┆           │
│ 21082682 ┆ MOOP           ┆ 39824   ┆ Ryan H.        ┆ moop          ┆ /league/nemel ┆ 27.177275 │
│          ┆                ┆         ┆                ┆               ┆ ee/player/76E ┆           │
│          ┆                ┆         ┆                ┆               ┆ 2BBC…         ┆           │
│ 21080350 ┆ Babs           ┆ 356016  ┆ Cameron G.     ┆ babs          ┆ /league/nemel ┆ 26.970908 │
│          ┆                ┆         ┆                ┆               ┆ ee/player/03D ┆           │
│          ┆                ┆         ┆                ┆               ┆ 1DA3…         ┆           │
│ 21083122 ┆ Byrne          ┆ 2926126 ┆ null           ┆ byrne         ┆ /league/nemel ┆ 26.277473 │
│          ┆                ┆         ┆                ┆               ┆ ee/player/9F8 ┆           │
│          ┆                ┆         ┆                ┆               ┆ AD0D…         ┆           │
│ 21082682 ┆ MOOP           ┆ 39824   ┆ Ryan H.        ┆ moop          ┆ /league/nemel ┆ 25.959842 │
│          ┆                ┆         ┆                ┆               ┆ ee/player/BBB ┆           │
│          ┆                ┆         ┆                ┆               ┆ 96C1…         ┆           │
│ 21080785 ┆ Duffy          ┆ 3166576 ┆ null           ┆ duffy         ┆ /league/nemel ┆ 24.242219 │
│          ┆                ┆         ┆                ┆               ┆ ee/player/806 ┆           │
│          ┆                ┆         ┆                ┆               ┆ 202F…         ┆           │
│ 21077283 ┆ Tpoz           ┆ 1001870 ┆ Pato Mora      ┆ tpoz          ┆ /league/nemel ┆ 24.11919  │
│          ┆                ┆         ┆                ┆               ┆ ee/player/E05 ┆           │
│          ┆                ┆         ┆                ┆               ┆ 3EA0…         ┆           │
│ 21082393 ┆ InDaHouse      ┆ 48367   ┆ Daniel Valadas ┆ indahouse     ┆ /league/nemel ┆ 24.003618 │
│          ┆                ┆         ┆                ┆               ┆ ee/player/A28 ┆           │
│          ┆                ┆         ┆                ┆               ┆ 7203…         ┆           │
│ 21071201 ┆ HotPeppers     ┆ 2074352 ┆ null           ┆ hotpeppers    ┆ /league/nemel ┆ 23.93138  │
│          ┆                ┆         ┆                ┆               ┆ ee/player/975 ┆           │
│          ┆                ┆         ┆                ┆               ┆ 1BF1…         ┆           │
│ 21081837 ┆ sfy bees       ┆ 34163   ┆ Tyler Sherer   ┆ sfy bees      ┆ /league/nemel ┆ 23.600913 │
│          ┆                ┆         ┆                ┆               ┆ ee/player/843 ┆           │
│          ┆                ┆         ┆                ┆               ┆ 4066…         ┆           │
│ 21081947 ┆ ren            ┆ 2792560 ┆ null           ┆ ren           ┆ /league/nemel ┆ 22.996601 │
│          ┆                ┆         ┆                ┆               ┆ ee/player/D22 ┆           │
│          ┆                ┆         ┆                ┆               ┆ 47C7…         ┆           │
│ 21083157 ┆ Cheezboom      ┆ 2762869 ┆ Jared B.       ┆ cheezboom     ┆ /league/nemel ┆ 22.501812 │
│          ┆                ┆         ┆                ┆               ┆ ee/player/5A1 ┆           │
│          ┆                ┆         ┆                ┆               ┆ 37D1…         ┆           │
│ 21071201 ┆ HotPeppers     ┆ 2074352 ┆ null           ┆ hotpeppers    ┆ /league/nemel ┆ 19.11829  │
│          ┆                ┆         ┆                ┆               ┆ ee/player/DD4 ┆           │
│          ┆                ┆         ┆                ┆               ┆ 6F7F…         ┆           │
│ 21082964 ┆ Petotae        ┆ 985473  ┆ Peter          ┆ petotae       ┆ /league/nemel ┆ 18.392367 │
│          ┆                ┆         ┆ Savinelli      ┆               ┆ ee/player/1F9 ┆           │
│          ┆                ┆         ┆                ┆               ┆ 2227…         ┆           │
│ 21081868 ┆ bfu            ┆ 2900434 ┆ null           ┆ bfu           ┆ /league/nemel ┆ 17.907315 │
│          ┆                ┆         ┆                ┆               ┆ ee/player/E8A ┆           │
│          ┆                ┆         ┆                ┆               ┆ 5E25…         ┆           │
│ 21082933 ┆ Lermonz        ┆ 614035  ┆ Lena Navin     ┆ lermonz       ┆ /league/nemel ┆ 15.167623 │
│          ┆                ┆         ┆                ┆               ┆ ee/player/47D ┆           │
│          ┆                ┆         ┆                ┆               ┆ EFF2…         ┆           │
│ 21079100 ┆ Idkwhattocallm ┆ 3147972 ┆ null           ┆ idkwhattocall ┆ /league/nemel ┆ 14.970317 │
│          ┆ yself          ┆         ┆                ┆ myself        ┆ ee/player/CEC ┆           │
│          ┆                ┆         ┆                ┆               ┆ 1F09…         ┆           │
│ 21083063 ┆ RoccoChief     ┆ 2426665 ┆ null           ┆ roccochief    ┆ /league/nemel ┆ 13.326954 │
│          ┆                ┆         ┆                ┆               ┆ ee/player/4E8 ┆           │
│          ┆                ┆         ┆                ┆               ┆ 2626…         ┆           │
│ 21080263 ┆ Eol            ┆ 3213021 ┆ null           ┆ eol           ┆ /league/nemel ┆ 11.47359  │
│          ┆                ┆         ┆                ┆               ┆ ee/player/630 ┆           │
│          ┆                ┆         ┆                ┆               ┆ C48E…         ┆           │
│ 21081697 ┆ coffee         ┆ 548818  ┆ Alex S.        ┆ coffee        ┆ /league/nemel ┆ 10.129804 │
│          ┆                ┆         ┆                ┆               ┆ ee/player/398 ┆           │
│          ┆                ┆         ┆                ┆               ┆ 719D…         ┆           │
│ 21079813 ┆ BoratNorad     ┆ 2767955 ┆ null           ┆ boratnorad    ┆ /league/nemel ┆ 8.86243   │
│          ┆                ┆         ┆                ┆               ┆ ee/player/90C ┆           │
│          ┆                ┆         ┆                ┆               ┆ D56B…         ┆           │
└──────────┴────────────────┴─────────┴────────────────┴───────────────┴───────────────┴───────────┘