# Get list of entrants

In [ ]:
tournament_slug = 'ngpr'
event_name = 'Melee Redemption'
event_name = 'Melee Singles'

In [51]:
import json
from gql import gql, Client
from gql.transport.requests import RequestsHTTPTransport

In [52]:
%%bash
source ~/.bashrc

In [53]:
import os

auth_token = os.environ['SMASHGG_TOKEN']
api_version = 'alpha'

In [54]:
transport = RequestsHTTPTransport(
    url=f'https://api.start.gg/gql/{api_version}',
    headers={'Authorization': f'Bearer {auth_token}'},
    use_json=True,
)

client = Client(transport=transport, fetch_schema_from_transport=False)

In [55]:
# Define the API endpoint and query for tournament details
query = gql("""
query TournamentQuery($slug: String!) {
    tournament(slug: $slug) {
        id
        name
        city
        state
        countryCode
        startAt
        endAt
        events {
            id
            name
            numEntrants
        }
    }
}
""")

variables = {"slug": tournament_slug}

# Execute the query
try:
        tournament_result = client.execute(query, variable_values=variables)
        print(json.dumps(tournament_result, indent=2))
except Exception as e:
        print("Error fetching tournament details:", e)

{
  "tournament": {
    "id": 810907,
    "name": "New Game Plus Revival 8.14",
    "city": "Boston",
    "state": 3,
    "countryCode": "US",
    "startAt": 1753218000,
    "endAt": 1753242960,
    "events": [
      {
        "id": 1422769,
        "name": "Melee Redemption",
        "numEntrants": 10
      },
      {
        "id": 1422770,
        "name": "Project+ Singles (Free!)",
        "numEntrants": 7
      },
      {
        "id": 1422768,
        "name": "Melee Singles",
        "numEntrants": 28
      }
    ]
  }
}

In [56]:
# Extract the event id for "Melee Singles"
events = tournament_result['tournament']['events']
melee_singles_id = next((event['id'] for event in events if event_name in event['name']), None)
print(f"{event_name} Event ID: {melee_singles_id}")

Melee Redemption Event ID: 1422769

In [8]:
# Query to get entrants for Melee Singles
entrants_query = gql("""
query EventEntrants($eventId: ID!) {
    event(id: $eventId) {
        entrants(query: {page: 1, perPage: 512}) {
            nodes {
                id
                name
                participants {
                    gamerTag
                }
            }
        }
    }
}
""")

entrants_variables = {"eventId": melee_singles_id}

try:
        entrants_result = client.execute(entrants_query, variable_values=entrants_variables)
        print(json.dumps(entrants_result, indent=2))
except Exception as e:
        print("Error fetching entrants:", e)

{
  "event": {
    "entrants": {
      "nodes": [
        {
          "id": 20771889,
          "name": "nahome tesfay",
          "participants": [
            {
              "gamerTag": "nahome tesfay"
            }
          ]
        },
        {
          "id": 20771760,
          "name": "MAIF",
          "participants": [
            {
              "gamerTag": "MAIF"
            }
          ]
        },
        {
          "id": 20771740,
          "name": "sfy | sfy bees",
          "participants": [
            {
              "gamerTag": "sfy bees"
            }
          ]
        },
        {
          "id": 20771458,
          "name": "SIX | Embry",
          "participants": [
            {
              "gamerTag": "Embry"
            }
          ]
        },
        {
          "id": 20771311,
          "name": "CF | JAVI ON EARTH",
          "participants": [
            {
              "gamerTag": "JAVI ON EARTH"
            }
          ]
        },
        {
          "id": 20771274,
          "name": "hc | saucymain",
          "participants": [
            {
              "gamerTag": "saucymain"
            }
          ]
        },
        {
          "id": 20771267,
          "name": "zeldEx",
          "participants": [
            {
              "gamerTag": "zeldEx"
            }
          ]
        },
        {
          "id": 20771178,
          "name": "\u30ac\u30c3\u30c4",
          "participants": [
            {
              "gamerTag": "\u30ac\u30c3\u30c4"
            }
          ]
        },
        {
          "id": 20771153,
          "name": "smoked_em",
          "participants": [
            {
              "gamerTag": "smoked_em"
            }
          ]
        },
        {
          "id": 20770577,
          "name": "bonfire10",
          "participants": [
            {
              "gamerTag": "bonfire10"
            }
          ]
        },
        {
          "id": 20770244,
          "name": "yungsos",
          "participants": [
            {
              "gamerTag": "yungsos"
            }
          ]
        },
        {
          "id": 20770038,
          "name": "Swartzy",
          "participants": [
            {
              "gamerTag": "Swartzy"
            }
          ]
        },
        {
          "id": 20769742,
          "name": "Eden",
          "participants": [
            {
              "gamerTag": "Eden"
            }
          ]
        },
        {
          "id": 20769680,
          "name": "Sweat",
          "participants": [
            {
              "gamerTag": "Sweat"
            }
          ]
        },
        {
          "id": 20769573,
          "name": "zaubermaus",
          "participants": [
            {
              "gamerTag": "zaubermaus"
            }
          ]
        },
        {
          "id": 20769483,
          "name": "Qwerty",
          "participants": [
            {
              "gamerTag": "Qwerty"
            }
          ]
        },
        {
          "id": 20769402,
          "name": "Vexoskeleton",
          "participants": [
            {
              "gamerTag": "Vexoskeleton"
            }
          ]
        },
        {
          "id": 20769115,
          "name": "Badboi",
          "participants": [
            {
              "gamerTag": "Badboi"
            }
          ]
        },
        {
          "id": 20768777,
          "name": "Ant",
          "participants": [
            {
              "gamerTag": "Ant"
            }
          ]
        },
        {
          "id": 20768222,
          "name": "Gambit",
          "participants": [
            {
              "gamerTag": "Gambit"
            }
          ]
        },
        {
          "id": 20767219,
          "name": "Motobug",
          "participants": [
            {
              "gamerTag": "Motobug"
            }
          ]
        },
        {
          "id": 20766877,
          "name": "AUNTIE WOW | bleop",
          "participants": [
            {
              "gamerTag": "bleop"
            }
          ]
        },
        {
          "id": 20766573,
          "name": "Monochrome",
          "participants": [
            {
              "gamerTag": "Monochrome"
            }
          ]
        },
        {
          "id": 20766183,
          "name": "Downey",
          "participants": [
            {
              "gamerTag": "Downey"
            }
          ]
        },
        {
          "id": 20762073,
          "name": "bfu",
          "participants": [
            {
              "gamerTag": "bfu"
            }
          ]
        },
        {
          "id": 20759616,
          "name": "MOOP",
          "participants": [
            {
              "gamerTag": "MOOP"
            }
          ]
        },
        {
          "id": 20759233,
          "name": "Smyles",
          "participants": [
            {
              "gamerTag": "Smyles"
            }
          ]
        },
        {
          "id": 20759060,
          "name": "Exarch",
          "participants": [
            {
              "gamerTag": "Exarch"
            }
          ]
        }
      ]
    }
  }
}

In [9]:
import polars as pl

# Extract entrant data and flatten participants' gamerTags

entrant_nodes = entrants_result['event']['entrants']['nodes']
data = []
for entrant in entrant_nodes:
    entrant_id = entrant['id']
    entrant_name = entrant['name']
    # There may be multiple participants per entrant; join their gamerTags with comma
    gamer_tags = [p['gamerTag'] for p in entrant.get('participants', [])]
    gamer_tag = ', '.join(gamer_tags)
    data.append({'id': entrant_id, 'name': entrant_name, 'gamertag': gamer_tag})

entrants = pl.DataFrame(data)
entrants

shape: (28, 3)
┌──────────┬────────────────────┬───────────────┐
│ id       ┆ name               ┆ gamertag      │
│ ---      ┆ ---                ┆ ---           │
│ i64      ┆ str                ┆ str           │
╞══════════╪════════════════════╪═══════════════╡
│ 20771889 ┆ nahome tesfay      ┆ nahome tesfay │
│ 20771760 ┆ MAIF               ┆ MAIF          │
│ 20771740 ┆ sfy | sfy bees     ┆ sfy bees      │
│ 20771458 ┆ SIX | Embry        ┆ Embry         │
│ 20771311 ┆ CF | JAVI ON EARTH ┆ JAVI ON EARTH │
│ …        ┆ …                  ┆ …             │
│ 20766183 ┆ Downey             ┆ Downey        │
│ 20762073 ┆ bfu                ┆ bfu           │
│ 20759616 ┆ MOOP               ┆ MOOP          │
│ 20759233 ┆ Smyles             ┆ Smyles        │
│ 20759060 ┆ Exarch             ┆ Exarch        │
└──────────┴────────────────────┴───────────────┘

In [10]:
entrant_gamertags = entrants.select(pl.col('gamertag').str.to_lowercase()).to_series().to_list()

# collect seeding

In [11]:
player_ratings = pl.read_parquet('data/player-ratings.parquet')

In [24]:
pl.Config(tbl_rows=100)
entrant_ratings = (
    entrants
    .with_columns(pl.col('gamertag').str.to_lowercase())
    .join(
        player_ratings
            .with_columns(pl.col('tag').str.split(' | ').list.last().str.to_lowercase()),
        how='full',
        left_on='gamertag',
        right_on='tag',
    )
    #.filter(
    #    (pl.col('tag').str.to_lowercase() == pl.col('gamertag').str.to_lowercase()) |
    #    pl.col('gamertag').is_null()
    #)
    .filter(pl.col('gamertag').is_not_null())
    .sort('rating', descending=True)
    .group_by('id').first()
    .fill_null(0)
    .sort('rating', descending=True)
)
display(entrant_ratings)

shape: (28, 6)
┌──────────┬────────────────────┬───────────────┬──────────────────────┬───────────┬───────────────┐
│ id       ┆ name               ┆ gamertag      ┆ url                  ┆ rating    ┆ tag           │
│ ---      ┆ ---                ┆ ---           ┆ ---                  ┆ ---       ┆ ---           │
│ i64      ┆ str                ┆ str           ┆ str                  ┆ f64       ┆ str           │
╞══════════╪════════════════════╪═══════════════╪══════════════════════╪═══════════╪═══════════════╡
│ 20770577 ┆ bonfire10          ┆ bonfire10     ┆ /league/nemelee/play ┆ 42.003164 ┆ bonfire10     │
│          ┆                    ┆               ┆ er/C9B8492…          ┆           ┆               │
│ 20768777 ┆ Ant                ┆ ant           ┆ /league/nemelee/play ┆ 35.631526 ┆ ant           │
│          ┆                    ┆               ┆ er/5DBCC34…          ┆           ┆               │
│ 20771274 ┆ hc | saucymain     ┆ saucymain     ┆ /league/nemelee/play ┆ 33.768498 ┆ saucymain     │
│          ┆                    ┆               ┆ er/2407F41…          ┆           ┆               │
│ 20769680 ┆ Sweat              ┆ sweat         ┆ /league/nemelee/play ┆ 32.880512 ┆ sweat         │
│          ┆                    ┆               ┆ er/DF3CE0B…          ┆           ┆               │
│ 20769115 ┆ Badboi             ┆ badboi        ┆ /league/nemelee/play ┆ 32.000816 ┆ badboi        │
│          ┆                    ┆               ┆ er/CDE68D1…          ┆           ┆               │
│ 20771267 ┆ zeldEx             ┆ zeldex        ┆ /league/nemelee/play ┆ 30.695035 ┆ zeldex        │
│          ┆                    ┆               ┆ er/DBA78EE…          ┆           ┆               │
│ 20768222 ┆ Gambit             ┆ gambit        ┆ /league/nemelee/play ┆ 30.626982 ┆ gambit        │
│          ┆                    ┆               ┆ er/62EEC11…          ┆           ┆               │
│ 20767219 ┆ Motobug            ┆ motobug       ┆ /league/nemelee/play ┆ 30.067921 ┆ motobug       │
│          ┆                    ┆               ┆ er/E12030B…          ┆           ┆               │
│ 20769573 ┆ zaubermaus         ┆ zaubermaus    ┆ /league/nemelee/play ┆ 29.015436 ┆ zaubermaus    │
│          ┆                    ┆               ┆ er/66DEE19…          ┆           ┆               │
│ 20770038 ┆ Swartzy            ┆ swartzy       ┆ /league/nemelee/play ┆ 27.052366 ┆ swartzy       │
│          ┆                    ┆               ┆ er/2D23DC1…          ┆           ┆               │
│ 20759616 ┆ MOOP               ┆ moop          ┆ /league/nemelee/play ┆ 26.920901 ┆ moop          │
│          ┆                    ┆               ┆ er/76E2BBC…          ┆           ┆               │
│ 20769742 ┆ Eden               ┆ eden          ┆ /league/nemelee/play ┆ 26.268877 ┆ eden          │
│          ┆                    ┆               ┆ er/F24B4BB…          ┆           ┆               │
│ 20766877 ┆ AUNTIE WOW | bleop ┆ bleop         ┆ /league/nemelee/play ┆ 25.299188 ┆ bleop         │
│          ┆                    ┆               ┆ er/9DABAEA…          ┆           ┆               │
│ 20769402 ┆ Vexoskeleton       ┆ vexoskeleton  ┆ /league/nemelee/play ┆ 25.027049 ┆ vexoskeleton  │
│          ┆                    ┆               ┆ er/96818C5…          ┆           ┆               │
│ 20771178 ┆ ガッツ             ┆ ガッツ        ┆ /league/nemelee/play ┆ 24.311066 ┆ ガッツ        │
│          ┆                    ┆               ┆ er/806202F…          ┆           ┆               │
│ 20766183 ┆ Downey             ┆ downey        ┆ /league/nemelee/play ┆ 23.8963   ┆ downey        │
│          ┆                    ┆               ┆ er/A749F70…          ┆           ┆               │
│ 20769483 ┆ Qwerty             ┆ qwerty        ┆ /league/nemelee/play ┆ 23.887112 ┆ qwerty        │
│          ┆                    ┆               ┆ er/19B79D7…          ┆           ┆               │
│ 20766573 ┆ Monochrome         ┆ monochrome    ┆ /league/nemelee/play ┆ 23.842565 ┆ monochrome    │
│          ┆                    ┆               ┆ er/849E9B3…          ┆           ┆               │
│ 20771740 ┆ sfy | sfy bees     ┆ sfy bees      ┆ /league/nemelee/play ┆ 23.150642 ┆ sfy bees      │
│          ┆                    ┆               ┆ er/8434066…          ┆           ┆               │
│ 20770244 ┆ yungsos            ┆ yungsos       ┆ /league/nemelee/play ┆ 21.489353 ┆ yungsos       │
│          ┆                    ┆               ┆ er/BC547FD…          ┆           ┆               │
│ 20759233 ┆ Smyles             ┆ smyles        ┆ /league/nemelee/play ┆ 19.436947 ┆ smyles        │
│          ┆                    ┆               ┆ er/24A071F…          ┆           ┆               │
│ 20762073 ┆ bfu                ┆ bfu           ┆ /league/nemelee/play ┆ 18.710744 ┆ bfu           │
│          ┆                    ┆               ┆ er/E8A5E25…          ┆           ┆               │
│ 20771458 ┆ SIX | Embry        ┆ embry         ┆ /league/nemelee/play ┆ 15.230232 ┆ embry         │
│          ┆                    ┆               ┆ er/320B476…          ┆           ┆               │
│ 20771889 ┆ nahome tesfay      ┆ nahome tesfay ┆ /league/nemelee/play ┆ 10.337628 ┆ nahome tesfay │
│          ┆                    ┆               ┆ er/13D92AA…          ┆           ┆               │
│ 20759060 ┆ Exarch             ┆ exarch        ┆ /league/nemelee/play ┆ 10.021742 ┆ exarch        │
│          ┆                    ┆               ┆ er/BD62470…          ┆           ┆               │
│ 20771760 ┆ MAIF               ┆ maif          ┆ /league/nemelee/play ┆ 9.120781  ┆ maif          │
│          ┆                    ┆               ┆ er/36266FF…          ┆           ┆               │
│ 20771311 ┆ CF | JAVI ON EARTH ┆ javi on earth ┆ null                 ┆ 0.0       ┆ null          │
│ 20771153 ┆ smoked_em          ┆ smoked_em     ┆ null                 ┆ 0.0       ┆ null          │
└──────────┴────────────────────┴───────────────┴──────────────────────┴───────────┴───────────────┘

In [25]:
entrant_seeding = (
    entrant_ratings
    .sort('rating', descending=True)
    .with_row_index('seed_num')
    .with_columns(pl.col('seed_num') + 1)
)
entrant_seeding

shape: (28, 7)
┌──────────┬──────────┬────────────────┬───────────────┬───────────────┬───────────┬───────────────┐
│ seed_num ┆ id       ┆ name           ┆ gamertag      ┆ url           ┆ rating    ┆ tag           │
│ ---      ┆ ---      ┆ ---            ┆ ---           ┆ ---           ┆ ---       ┆ ---           │
│ u32      ┆ i64      ┆ str            ┆ str           ┆ str           ┆ f64       ┆ str           │
╞══════════╪══════════╪════════════════╪═══════════════╪═══════════════╪═══════════╪═══════════════╡
│ 1        ┆ 20770577 ┆ bonfire10      ┆ bonfire10     ┆ /league/nemel ┆ 42.003164 ┆ bonfire10     │
│          ┆          ┆                ┆               ┆ ee/player/C9B ┆           ┆               │
│          ┆          ┆                ┆               ┆ 8492…         ┆           ┆               │
│ 2        ┆ 20768777 ┆ Ant            ┆ ant           ┆ /league/nemel ┆ 35.631526 ┆ ant           │
│          ┆          ┆                ┆               ┆ ee/player/5DB ┆           ┆               │
│          ┆          ┆                ┆               ┆ CC34…         ┆           ┆               │
│ 3        ┆ 20771274 ┆ hc | saucymain ┆ saucymain     ┆ /league/nemel ┆ 33.768498 ┆ saucymain     │
│          ┆          ┆                ┆               ┆ ee/player/240 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 7F41…         ┆           ┆               │
│ 4        ┆ 20769680 ┆ Sweat          ┆ sweat         ┆ /league/nemel ┆ 32.880512 ┆ sweat         │
│          ┆          ┆                ┆               ┆ ee/player/DF3 ┆           ┆               │
│          ┆          ┆                ┆               ┆ CE0B…         ┆           ┆               │
│ 5        ┆ 20769115 ┆ Badboi         ┆ badboi        ┆ /league/nemel ┆ 32.000816 ┆ badboi        │
│          ┆          ┆                ┆               ┆ ee/player/CDE ┆           ┆               │
│          ┆          ┆                ┆               ┆ 68D1…         ┆           ┆               │
│ 6        ┆ 20771267 ┆ zeldEx         ┆ zeldex        ┆ /league/nemel ┆ 30.695035 ┆ zeldex        │
│          ┆          ┆                ┆               ┆ ee/player/DBA ┆           ┆               │
│          ┆          ┆                ┆               ┆ 78EE…         ┆           ┆               │
│ 7        ┆ 20768222 ┆ Gambit         ┆ gambit        ┆ /league/nemel ┆ 30.626982 ┆ gambit        │
│          ┆          ┆                ┆               ┆ ee/player/62E ┆           ┆               │
│          ┆          ┆                ┆               ┆ EC11…         ┆           ┆               │
│ 8        ┆ 20767219 ┆ Motobug        ┆ motobug       ┆ /league/nemel ┆ 30.067921 ┆ motobug       │
│          ┆          ┆                ┆               ┆ ee/player/E12 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 030B…         ┆           ┆               │
│ 9        ┆ 20769573 ┆ zaubermaus     ┆ zaubermaus    ┆ /league/nemel ┆ 29.015436 ┆ zaubermaus    │
│          ┆          ┆                ┆               ┆ ee/player/66D ┆           ┆               │
│          ┆          ┆                ┆               ┆ EE19…         ┆           ┆               │
│ 10       ┆ 20770038 ┆ Swartzy        ┆ swartzy       ┆ /league/nemel ┆ 27.052366 ┆ swartzy       │
│          ┆          ┆                ┆               ┆ ee/player/2D2 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 3DC1…         ┆           ┆               │
│ 11       ┆ 20759616 ┆ MOOP           ┆ moop          ┆ /league/nemel ┆ 26.920901 ┆ moop          │
│          ┆          ┆                ┆               ┆ ee/player/76E ┆           ┆               │
│          ┆          ┆                ┆               ┆ 2BBC…         ┆           ┆               │
│ 12       ┆ 20769742 ┆ Eden           ┆ eden          ┆ /league/nemel ┆ 26.268877 ┆ eden          │
│          ┆          ┆                ┆               ┆ ee/player/F24 ┆           ┆               │
│          ┆          ┆                ┆               ┆ B4BB…         ┆           ┆               │
│ 13       ┆ 20766877 ┆ AUNTIE WOW |   ┆ bleop         ┆ /league/nemel ┆ 25.299188 ┆ bleop         │
│          ┆          ┆ bleop          ┆               ┆ ee/player/9DA ┆           ┆               │
│          ┆          ┆                ┆               ┆ BAEA…         ┆           ┆               │
│ 14       ┆ 20769402 ┆ Vexoskeleton   ┆ vexoskeleton  ┆ /league/nemel ┆ 25.027049 ┆ vexoskeleton  │
│          ┆          ┆                ┆               ┆ ee/player/968 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 18C5…         ┆           ┆               │
│ 15       ┆ 20771178 ┆ ガッツ         ┆ ガッツ        ┆ /league/nemel ┆ 24.311066 ┆ ガッツ        │
│          ┆          ┆                ┆               ┆ ee/player/806 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 202F…         ┆           ┆               │
│ 16       ┆ 20766183 ┆ Downey         ┆ downey        ┆ /league/nemel ┆ 23.8963   ┆ downey        │
│          ┆          ┆                ┆               ┆ ee/player/A74 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 9F70…         ┆           ┆               │
│ 17       ┆ 20769483 ┆ Qwerty         ┆ qwerty        ┆ /league/nemel ┆ 23.887112 ┆ qwerty        │
│          ┆          ┆                ┆               ┆ ee/player/19B ┆           ┆               │
│          ┆          ┆                ┆               ┆ 79D7…         ┆           ┆               │
│ 18       ┆ 20766573 ┆ Monochrome     ┆ monochrome    ┆ /league/nemel ┆ 23.842565 ┆ monochrome    │
│          ┆          ┆                ┆               ┆ ee/player/849 ┆           ┆               │
│          ┆          ┆                ┆               ┆ E9B3…         ┆           ┆               │
│ 19       ┆ 20771740 ┆ sfy | sfy bees ┆ sfy bees      ┆ /league/nemel ┆ 23.150642 ┆ sfy bees      │
│          ┆          ┆                ┆               ┆ ee/player/843 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 4066…         ┆           ┆               │
│ 20       ┆ 20770244 ┆ yungsos        ┆ yungsos       ┆ /league/nemel ┆ 21.489353 ┆ yungsos       │
│          ┆          ┆                ┆               ┆ ee/player/BC5 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 47FD…         ┆           ┆               │
│ 21       ┆ 20759233 ┆ Smyles         ┆ smyles        ┆ /league/nemel ┆ 19.436947 ┆ smyles        │
│          ┆          ┆                ┆               ┆ ee/player/24A ┆           ┆               │
│          ┆          ┆                ┆               ┆ 071F…         ┆           ┆               │
│ 22       ┆ 20762073 ┆ bfu            ┆ bfu           ┆ /league/nemel ┆ 18.710744 ┆ bfu           │
│          ┆          ┆                ┆               ┆ ee/player/E8A ┆           ┆               │
│          ┆          ┆                ┆               ┆ 5E25…         ┆           ┆               │
│ 23       ┆ 20771458 ┆ SIX | Embry    ┆ embry         ┆ /league/nemel ┆ 15.230232 ┆ embry         │
│          ┆          ┆                ┆               ┆ ee/player/320 ┆           ┆               │
│          ┆          ┆                ┆               ┆ B476…         ┆           ┆               │
│ 24       ┆ 20771889 ┆ nahome tesfay  ┆ nahome tesfay ┆ /league/nemel ┆ 10.337628 ┆ nahome tesfay │
│          ┆          ┆                ┆               ┆ ee/player/13D ┆           ┆               │
│          ┆          ┆                ┆               ┆ 92AA…         ┆           ┆               │
│ 25       ┆ 20759060 ┆ Exarch         ┆ exarch        ┆ /league/nemel ┆ 10.021742 ┆ exarch        │
│          ┆          ┆                ┆               ┆ ee/player/BD6 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 2470…         ┆           ┆               │
│ 26       ┆ 20771760 ┆ MAIF           ┆ maif          ┆ /league/nemel ┆ 9.120781  ┆ maif          │
│          ┆          ┆                ┆               ┆ ee/player/362 ┆           ┆               │
│          ┆          ┆                ┆               ┆ 66FF…         ┆           ┆               │
│ 27       ┆ 20771311 ┆ CF | JAVI ON   ┆ javi on earth ┆ null          ┆ 0.0       ┆ null          │
│          ┆          ┆ EARTH          ┆               ┆               ┆           ┆               │
│ 28       ┆ 20771153 ┆ smoked_em      ┆ smoked_em     ┆ null          ┆ 0.0       ┆ null          │
└──────────┴──────────┴────────────────┴───────────────┴───────────────┴───────────┴───────────────┘

# Export seeding to start gg

In [14]:
# Query to get phase IDs for Melee Singles event
phases_query = gql("""
query EventPhases($eventId: ID!) {
    event(id: $eventId) {
        phases {
            id
            name
            numSeeds
        }
    }
}
""")

phases_variables = {"eventId": melee_singles_id}

try:
        phases_result = client.execute(phases_query, variable_values=phases_variables)
        print(json.dumps(phases_result, indent=2))
except Exception as e:
        print("Error fetching phases:", e)

phase_id = phases_result['event']['phases'][0]['id']
print(f'phase id: {phase_id}')

{
  "event": {
    "phases": [
      {
        "id": 2028888,
        "name": "Bracket",
        "numSeeds": 28
      }
    ]
  }
}
phase id: 2028888

In [15]:
# ...existing code...

# 1. Fetch seeds for the phase
seeds_query = gql("""
query PhaseSeeds($phaseId: ID!) {
  phase(id: $phaseId) {
    seeds(query: {perPage: 512}) {
      nodes {
        id
        entrant {
          id
        }
      }
    }
  }
}
""")
seeds_result = client.execute(seeds_query, variable_values={"phaseId": phase_id})
seed_nodes = seeds_result["phase"]["seeds"]["nodes"]
entrantid_to_seedid = {seed["entrant"]["id"]: seed["id"] for seed in seed_nodes}

# 2. Prepare seed mapping using correct seedId
seed_mapping = []
for row in entrant_seeding.iter_rows(named=True):
    entrant_id = int(row["id"])
    seed_id = entrantid_to_seedid.get(entrant_id)
    if seed_id:
        seed_mapping.append({
            "seedId": seed_id,
            "seedNum": row["seed_num"],
        })
    else:
        print(f"Warning: No seed found for entrant {entrant_id}")

print(f"Importing {len(seed_mapping)} seeds to phase {phase_id}...")

Importing 26 seeds to phase 2028888...

In [16]:
entrant_seeding = (
    entrant_seeding
    .with_columns(pl.col('id').map_elements(lambda x: entrantid_to_seedid.get(x, None)).alias('seed_id'))
)

/tmp/ipykernel_22710/1705157941.py:3: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
  .with_columns(pl.col('id').map_elements(lambda x: entrantid_to_seedid.get(x, None)).alias('seed_id'))

In [17]:
# Prepare seed mapping from entrant_ratings for the phase
seed_mapping = []
for row in entrant_seeding.iter_rows(named=True):
    seed_mapping.append({
        "seedId": row["seed_id"],
        "seedNum": row['seed_num'],
    })

print(f"Importing {len(seed_mapping)} seeds to phase {phase_id}...")

mutation = gql("""
mutation UpdatePhaseSeeding($phaseId: ID!, $seedMapping: [UpdatePhaseSeedInfo]!) {
  updatePhaseSeeding(phaseId: $phaseId, seedMapping: $seedMapping) {
    id
  }
}
""")

params = {
    "phaseId": phase_id,
    "seedMapping": seed_mapping,
}

try:
    result = client.execute(mutation, variable_values=params)
    print('Success!')
    print(result)
except Exception as e:
    print('Error:', e)

Importing 26 seeds to phase 2028888...
Error: {'message': 'Cannot modify seeds in started pools', 'extensions': {'category': 'validation'}, 'locations': [{'line': 2, 'column': 3}], 'path': ['updatePhaseSeeding'], 'type': 'validation', 'fields': None, 'fieldErrors': []}

# view previous tournaments by player

In [18]:
player = 'smoked_em'

In [19]:
from IPython.display import display, HTML

def display_side_by_side(*args, titles=('',)):
    html_str = ''
    if len(titles) > 0:
        html_str += '<div style="display:flex">'
    for df, title in zip(args, titles + ('',) * (len(args) - len(titles))):
        html_str += '<div style="margin-right:20px">'
        if title:
            html_str += f'<h2>{title}</h2>'
        html_str += df.to_html()
        html_str += '</div>'
    html_str += '</div>'
    display(HTML(html_str))

In [20]:
matches = pl.read_csv('data/matches-with-ratings.csv')

In [21]:
last_n_matches = (
    matches
    .filter(
        pl.col('winner').str.to_lowercase().str.contains(player.lower()) |
        pl.col('loser').str.to_lowercase().str.contains(player.lower())
    )
    .sort('tournament_date', 'encounter_id', descending=True)
    .head(40)
)
losses = (
    last_n_matches
    .filter(pl.col('loser').str.to_lowercase().str.contains(player.lower()))
    .select(
        pl.col('winner').alias('tag'),
        'winner_rating',
        'tournament_name',
        'tournament_date',
    )
    .sort('winner_rating', descending=False)
)
wins = (
    last_n_matches
    .filter(pl.col('winner').str.to_lowercase().str.contains(player.lower()))
    .select(
        pl.col('loser').alias('tag'),
        'loser_rating',
        'tournament_name',
        'tournament_date',
    )
    .sort('loser_rating', descending=True)
)
display_side_by_side(
    losses.to_pandas(),
    wins.to_pandas(),
    titles=('Losses', 'Wins')
)