In [ ]:
import os
import re
import time
import hashlib
from typing import Dict, Iterable, List, Optional
import requests
import pandas as pd

STARTGG_API_URL = "https://api.start.gg/gql/alpha"
STARTGG_API_KEY = os.getenv("START_GG_API_KEY") or os.getenv("SMASHGG_TOKEN")

if not STARTGG_API_KEY:
    raise ValueError("Missing START_GG_API_KEY or SMASHGG_TOKEN in environment")

HEADERS = {
    "Authorization": f"Bearer {STARTGG_API_KEY}",
    "Content-Type": "application/json",
    "Accept": "application/json",
}

AUTH_TYPES = ["DISCORD", "TWITTER", "TWITCH"]

def gql(query: str, variables: Optional[Dict] = None, timeout: int = 30) -> Dict:
    payload = {"query": query, "variables": variables or {}}
    response = requests.post(STARTGG_API_URL, headers=HEADERS, json=payload, timeout=timeout)
    response.raise_for_status()
    data = response.json()
    if "errors" in data:
        raise RuntimeError(data["errors"])
    return data

def extract_startgg_path(url_or_slug: str) -> str:
    match = re.search(r"(?:https?://)?(?:www\.)?(?:start|smash)\.gg/(.+)", url_or_slug.strip())
    if match:
        return match.group(1).strip("/")
    return url_or_slug.strip().strip("/")

def is_event_slug(slug: str) -> bool:
    return "/event/" in slug

def normalize_tournament_slug(slug_or_url: str) -> str:
    path = extract_startgg_path(slug_or_url)
    if path.startswith("tournament/"):
        return path
    if path.startswith("event/"):
        return f"tournament/{path}"
    return f"tournament/{path}"

def resolve_event_slug(tournament_slug: str, event_name_contains: Optional[str] = None) -> str:
    query = """
    query TournamentEvents($slug: String) {
      tournament(slug: $slug) {
        events {
          id
          name
          slug
        }
      }
    }
    """
    data = gql(query, {"slug": tournament_slug})
    events = (data.get("data", {}).get("tournament", {}) or {}).get("events", [])
    if not events:
        raise ValueError(f"No events found for tournament slug: {tournament_slug}")
    if event_name_contains:
        target = event_name_contains.lower()
        for event in events:
            if target in (event.get("name") or "").lower():
                return event["slug"]
    if len(events) == 1:
        return events[0]["slug"]
    raise ValueError(f"Multiple events found for {tournament_slug}; set event_name_contains")

def resolve_event_from_url(url_or_slug: str, event_name_contains: Optional[str] = None) -> str:
    path = extract_startgg_path(url_or_slug)
    if is_event_slug(path):
        return path
    tournament_slug = normalize_tournament_slug(path)
    return resolve_event_slug(tournament_slug, event_name_contains=event_name_contains)

def normalize_tag(value: Optional[str]) -> Optional[str]:
    if value is None:
        return None
    text = str(value).strip().lower()
    if not text:
        return None
    if "|" in text:
        text = text.split("|")[-1].strip()
    text = re.sub(r"[^a-z0-9]+", "", text)
    return text or None

def fetch_event_attendees(event_slug: str, per_page: int = 60, delay_s: float = 0.2) -> List[Dict]:
    query = """
    query EventEntrants($slug: String, $page: Int, $perPage: Int) {
      event(slug: $slug) {
        id
        name
        entrants(query: {page: $page, perPage: $perPage}) {
          pageInfo {
            total
            totalPages
            page
            perPage
          }
          nodes {
            id
            name
            participants {
              id
              gamerTag
              prefix
              user {
                id
                slug
                authorizations(types: [DISCORD, TWITTER, TWITCH]) {
                  type
                  externalUsername
                }
              }
            }
          }
        }
      }
    }
    """
    results: List[Dict] = []
    page = 1
    total_pages = 1
    while page <= total_pages:
        data = gql(query, {"slug": event_slug, "page": page, "perPage": per_page})
        event = data.get("data", {}).get("event")
        if not event:
            raise ValueError(f"Event not found: {event_slug}")
        entrants = (event.get("entrants") or {}).get("nodes", [])
        page_info = (event.get("entrants") or {}).get("pageInfo", {})
        total_pages = page_info.get("totalPages") or 1
        for entrant in entrants:
            entrant_id = entrant.get("id")
            entrant_name = entrant.get("name")
            entrant_id_sha256 = (
                hashlib.sha256(str(entrant_id).encode("utf-8")).hexdigest()
                if entrant_id is not None
                else None
            )
            assignment = (int(entrant_id_sha256, 16) % 3) if entrant_id_sha256 is not None else None
            for participant in (entrant.get("participants") or []):
                user = participant.get("user") or {}
                auths = {
                    auth.get("type"): auth.get("externalUsername")
                    for auth in (user.get("authorizations") or [])
                }
                record = {
                    "event_slug": event_slug,
                    "event_name": event.get("name"),
                    "entrant_id": entrant_id,
                    "entrant_id_sha256": entrant_id_sha256,
                    "assignment": assignment,
                    "entrant_name": entrant_name,
                    "participant_id": participant.get("id"),
                    "gamer_tag": participant.get("gamerTag"),
                    "prefix": participant.get("prefix"),
                    "user_id": user.get("id"),
                    "user_slug": user.get("slug"),
                    "discord": auths.get("DISCORD"),
                    "twitter": auths.get("TWITTER"),
                    "twitch": auths.get("TWITCH"),
                    "youtube": None,
                }
                results.append(record)
        page += 1
        time.sleep(delay_s)
    return results

def build_attendee_df(urls: Iterable[str], event_name_contains: Optional[str] = None) -> pd.DataFrame:
    rows: List[Dict] = []
    for url in urls:
        event_slug = resolve_event_from_url(url, event_name_contains=event_name_contains)
        rows.extend(fetch_event_attendees(event_slug))
    df = pd.DataFrame(rows)
    if df.empty:
        return df
    df["norm_gamer_tag"] = df["gamer_tag"].apply(normalize_tag)
    df["norm_entrant_name"] = df["entrant_name"].apply(normalize_tag)
    def row_key(row: pd.Series) -> Optional[str]:
        if pd.notna(row.get("user_id")):
            return f"user:{row['user_id']}"
        if pd.notna(row.get("user_slug")):
            return f"user_slug:{row['user_slug']}"
        if pd.notna(row.get("discord")):
            return f"discord:{str(row['discord']).lower()}"
        if pd.notna(row.get("twitter")):
            return f"twitter:{str(row['twitter']).lower()}"
        if pd.notna(row.get("twitch")):
            return f"twitch:{str(row['twitch']).lower()}"
        if pd.notna(row.get("norm_gamer_tag")):
            return f"tag:{row['norm_gamer_tag']}"
        if pd.notna(row.get("norm_entrant_name")):
            return f"entrant:{row['norm_entrant_name']}"
        return None
    df["key"] = df.apply(row_key, axis=1)
    return df

In [3]:
previous_tournaments = [
    # ngpr
    'https://www.start.gg/tournament/new-game-plus-revival-9-11',
    'https://www.start.gg/tournament/new-game-plus-revival-9-12',
    'https://www.start.gg/tournament/new-game-plus-revival-9-13',
    'https://www.start.gg/tournament/new-game-plus-revival-9-14',
    'https://www.start.gg/tournament/new-game-plus-revival-9-15',
    # allston allstars
    'https://www.start.gg/tournament/allston-allstars-vi-1',
    'https://www.start.gg/tournament/allston-allstars-v-tom-s-birthday-bash',
]
new_tournament = 'https://www.start.gg/tournament/allston-allstars-vi-1'

In [4]:
event_name_contains = "Melee Singles"  # Update if your target event uses a different name.

previous_df = build_attendee_df(previous_tournaments, event_name_contains=event_name_contains)
new_df = build_attendee_df([new_tournament], event_name_contains=event_name_contains)

if previous_df.empty:
    raise ValueError("No attendees found for previous tournaments")
if new_df.empty:
    raise ValueError("No attendees found for new tournament")

new_user_ids = set(new_df["user_id"].dropna().unique())
prospective_df = previous_df[~previous_df["user_id"].isin(new_user_ids)].copy()

prospective_df = prospective_df.drop_duplicates(subset=["user_id", "gamer_tag", "entrant_name"])
prospective_df = prospective_df.sort_values(["gamer_tag", "entrant_name"]).reset_index(drop=True)

prospective_df[
    [
        "assignment",
        "gamer_tag",
        "prefix",
        "entrant_name",
        "discord",
        "twitter",
        "twitch",
        "youtube",
    ]
]

,assignment,gamer_tag,prefix,entrant_name,discord,twitter,twitch,youtube
0,1,Andrew,None,Andrew,Padna#3980,None,None,None
1,0,Arty,HoG,HoG | Arty,Arty#5971,HoG_Arty,HoG_Arty,None
2,0,BBron,BU,BU | BBron,None,None,None,None
3,2,Babs,hc,hc | Babs,babs#5612,None,smokingrockwithmyangel,None
4,0,Bank,$G|MP,$G|MP | Bank,None,None,ssbmbank,None
...,...,...,...,...,...,...,...,...
95,1,viole,,viole,None,None,None,None
96,1,wons,PFC,PFC | wons,vwunsie,None,None,None
97,1,wons,so-po,so-po | wons,vwunsie,None,None,None
98,2,wub,None,wub,conwub#1971,None,None,None
99,1,zip zip,None,zip zip,Zip Zip Dpon648#8906,None,None,None

In [5]:
intersection_user_ids = set(previous_df["user_id"].dropna().unique()) & set(new_df["user_id"].dropna().unique())
pd.DataFrame({"user_id": sorted(intersection_user_ids)})

    user_id
0       409
1      7545
2     12545
3     17294
4     30419
5     34096
6     39824
7     43464
8     45427
9     95586
10   107947
11   146174
12   149864
13   177939
14   186663
15   305778
16   360588
17   384558
18   434591
19   465668
20   469917
21   485704
22   548818
23   561015
24   701249
25   717730
26   730677
27   997208
28  1013876
29  1081795
30  1409393
31  1658344
32  1877160
33  1911885
34  1946322
35  2361261
36  2549192
37  2767955
38  2792560
39  2879957
40  2900434
41  2926126
42  3097137
43  3119896
44  3152296
45  3228903

In [6]:
prospective_df[
    [
        "assignment",
        "gamer_tag",
        "prefix",
        "entrant_name",
        "discord",
        "twitter",
        "twitch",
        "youtube",
    ]
].to_csv("prospective_attendees.csv", index=False)

In [10]:
prospective_df.query('gamer_tag == "Essence"')

,event_slug,event_name,entrant_id,entrant_id_sha256,assignment,entrant_name,participant_id,gamer_tag,prefix,user_id,user_slug,discord,twitter,twitch,youtube,norm_gamer_tag,norm_entrant_name,key
26,tournament/allston-allstars-v-tom-s-birthday-b...,Melee Singles,20587334,f76c7f44019c2d0107bd1196b6c5c464c01c4718ab1424...,2,Essence,18953928,Essence,None,2336818.0,user/b2af438e,yeetcheng,None,None,None,essence,essence,user:2336818.0

In [8]:
new_df

,event_slug,event_name,entrant_id,entrant_id_sha256,assignment,entrant_name,participant_id,gamer_tag,prefix,user_id,user_slug,discord,twitter,twitch,youtube,norm_gamer_tag,norm_entrant_name,key
0,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22764017,08ef2c4e7b2059d9917247b3437dd7b0cae009d1efa2ab...,1,hc | keke,20916154,keke,hc,34096,user/4864af7d,None,None,None,None,keke,keke,user:34096
1,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22762621,7074ec149bd4394334c13535a0e9e0892f952823317676...,0,MEAT,20914981,MEAT,,177939,user/abbe7832,None,None,None,None,meat,meat,user:177939
2,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22759957,a3997d0b5be6f565a8aea898d4459831a7802ce0506b88...,0,Frostie,20912511,Frostie,,3119896,user/3abaa55a,frostyshart,None,None,None,frostie,frostie,user:3119896
3,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22759640,17e80db5c69d95de2983bc3398004e9c56895518a95668...,0,hc | chery*,20912199,chery*,hc,465668,user/396ed5a7,vers_fn,None,None,None,chery,chery,user:465668
4,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22759358,c917d15a1b9089f137feb43970e82200117fdff7bc75d7...,2,Danimals,20911945,Danimals,None,43464,user/5037fe60,None,None,None,None,danimals,danimals,user:43464
5,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22758685,99603a0e6edcf996c018c61b443377a16e560d7f1b9a8d...,1,BUG | Mimes,20911415,Mimes,BUG,2549192,user/4310c026,None,None,None,None,mimes,mimes,user:2549192
6,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22758484,27e13c6a81ab37793f7f4d8831ab09a74ba7d5def9b2f3...,1,Ant,20911278,Ant,None,7545,user/36e92bc4,antssbm,YUNGTRINITRON,AntMelee,None,ant,ant,user:7545
7,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22757472,9532e77efc9dd8caaf49f41f28ab0a85014a5cc7649a0e...,2,joe chemo,20910453,joe chemo,,701249,user/18d752ee,jesusgodmatt,None,None,None,joechemo,joechemo,user:701249
8,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22756181,c950bfc630752b79e431dafdb3106f4d3ab7a2e1886606...,0,OUG | Electroman,20909235,Electroman,OUG,149864,user/11625314,Electroman#3030,Electroman_DrAl,ElectromanSSB,None,electroman,electroman,user:149864
9,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22755495,0d13c4184cfcad896bccb72bf5bd9c0642b7dfd2929261...,2,hc | pluto,20908601,pluto,hc,717730,user/dabc0208,None,None,None,None,pluto,pluto,user:717730
10,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22754897,318e411ef151a0a0b733fe0d7745fd096ac63675ce4f28...,2,mint,20908068,mint,None,469917,user/77373213,SioBibble#6051,None,None,None,mint,mint,user:469917
11,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22754155,d63ff002d1d3c31404fa98485f75952415bebc8f04cb88...,1,regEx,20907431,regEx,,30419,user/b2c47396,regEx#0523,regEx_ssbm,regEx_melee,None,regex,regex,user:30419
12,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22753937,3a8aa995d02808b016aab0963a09c77f7b36feb78b4086...,1,glock in my toyota,20907256,glock in my toyota,None,384558,user/a7533abc,glock in my toyota#6273,glockSMB,None,None,glockinmytoyota,glockinmytoyota,user:384558
13,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22752656,9f8c641105b0fad7b3949ab8f90379d1b0c99af0374b89...,2,hc | Coolslice,20814403,Coolslice,hc,146174,user/161d08c2,Coolslice#5717,coolslice7,Coolslice7,None,coolslice,coolslice,user:146174
14,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22752208,573c69ad177c06a8a56a016eea3514f69f71834739609d...,1,hc | Good1ife,20905730,Good1ife,hc,561015,user/b00c5480,good1ife,None,good1ife_,None,good1ife,good1ife,user:561015
15,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22751424,5c6c9f3486469d1305437c4ec76d7201e92ec05fda593c...,1,TSI | coffee,20905007,coffee,TSI,548818,user/0046c6b3,None,None,None,None,coffee,coffee,user:548818
16,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22746433,12630911af416add80f62564dc96677b43d47c50ef6094...,2,MIAMI,20900354,MIAMI,,485704,user/7d00125e,None,None,None,None,miami,miami,user:485704
17,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22743132,3cfc5a88615cb137567815c52520e048c8511b0ba7d6d0...,1,chl0rine,20897374,chl0rine,,1409393,user/9391f3ad,chl0rine4815,None,chl0rine_ssbm,None,chl0rine,chl0rine,user:1409393
18,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22728111,f3352e2929a8ea3b694af953f1161e729d9f9876fc108e...,2,Frootbat,20883456,Frootbat,None,1013876,user/bc953e40,ThePeepeeFairy#8741,None,None,None,frootbat,frootbat,user:1013876
19,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22719114,050778e3dfdba80cec0b48bde6480b81c3200622d10580...,2,BRamZ,20875120,BRamZ,None,730677,user/0393b9e8,bradybunchfan,None,None,None,bramz,bramz,user:730677
20,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22718897,b43d671ad5d504d2417573a22731a5caad9d9018222867...,0,BoratNorad,20874911,BoratNorad,,2767955,user/29fa119a,boratnorad,None,None,None,boratnorad,boratnorad,user:2767955
21,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22718894,3a9b3b40e042743e8ead6e43f25f6efb6c2a6a938f2834...,0,BUG | Carmine,20874909,Carmine,BUG,3152296,user/69ba53d7,None,None,None,None,carmine,carmine,user:3152296
22,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22718882,81451bc00f695f77aef4a68a8f1379b1250caaa1e3c4d8...,1,BUG | spiderspud,20874895,spiderspud,BUG,3228903,user/f9a30868,spiderspud129,TheSpud129,spiderspud129,None,spiderspud,spiderspud,user:3228903
23,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22708872,ae27128e2c0f3faa79b5c2786fed9e175179a7ab29f38a...,0,oz,20865812,oz,None,45427,user/c08707cb,None,None,None,None,oz,oz,user:45427
24,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22706796,9abd8689e8aee1acf2af28628bad76afac98c639e52ce0...,0,Visual Cortex | w/ how I got 2 corny yuh,20864074,w/ how I got 2 corny yuh,Visual Cortex,95586,user/667984fa,None,None,None,None,whowigot2cornyyuh,whowigot2cornyyuh,user:95586
25,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22703563,f90df4489832997f0b09e2d6fa571484a33e23f92b39d7...,2,zaubermaus,20861144,zaubermaus,,305778,user/0a76d369,zauberrat,None,None,None,zaubermaus,zaubermaus,user:305778
26,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22699920,81128d3fc05dd6ddaa46af4989e43df569a5cab0b63b4a...,2,NEU | cybert,20858008,cybert,NEU,1946322,user/e8d669b2,cy.bert,None,None,None,cybert,cybert,user:1946322
27,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22687745,aac3d202c788954fce8cea4495f611788748987ecdf066...,2,Kuges,20848640,Kuges,,1081795,user/143d455f,kuges_,None,None,None,kuges,kuges,user:1081795
28,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22687202,35f16c8e75763eb81d1c1b14f220c2b40c7395a03ddcef...,0,stir fried,20848152,stir fried,None,1911885,user/de44763a,mick65.,None,None,None,stirfried,stirfried,user:1911885
29,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22678695,873bf7c7d87781b28edcc9f59b88bb65810478b63010ca...,1,bfu,20840613,bfu,None,2900434,user/91ba9594,None,None,None,None,bfu,bfu,user:2900434
30,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22678579,7720f50dfa5846c63e8b3d33bb0e683f92df064f3b53cd...,0,KBK | ren,20840509,ren,KBK,2792560,user/85e021f4,renwitdashifts,renwitdashifts,renwitdashifts,None,ren,ren,user:2792560
31,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22660275,d3c3a624c294dcfe918d2bac2b04cd01a902e1df9e199d...,1,Wishy,20824446,Wishy,,2879957,user/83fcc047,None,None,None,None,wishy,wishy,user:2879957
32,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22658228,526b78cbfae56894dd20771e2a36bb1e871ef26f478f15...,0,hc | PajamaPal,20822708,PajamaPal,hc,434591,user/17a303f0,pajamapal,None,PapaPajama,None,pajamapal,pajamapal,user:434591
33,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22634998,00af5772d6494f8a6655374a948f12490eb9276169c822...,2,brennan,20802524,brennan,,2361261,user/9bc710eb,__brennan,None,None,None,brennan,brennan,user:2361261
34,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22615808,0d1635c153dad5acc2008e042321700cf88cf380f0fd18...,2,Qwerty,20786006,Qwerty,None,107947,user/b9853b93,Qwerty#7507,None,None,None,qwerty,qwerty,user:107947
35,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22572588,d9f5e15672b98e5ba66dc9ca50ee7db6b649739a1f5a1a...,1,henghost,20748487,henghost,None,186663,user/d1cb6cf6,None,None,None,None,henghost,henghost,user:186663
36,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22572565,f3e3e96cd5a63b32c367714b92dfda3fa448e446efc478...,0,Blue Velvet,20748468,Blue Velvet,,997208,user/10af6f8f,bluevelvetssbm,None,None,None,bluevelvet,bluevelvet,user:997208
37,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22525412,2747a4432bf50876c721c24cca5478281e8e0d6439ce3c...,2,Byrne,20707343,Byrne,None,2926126,user/fc45cec4,byrne__,None,None,None,byrne,byrne,user:2926126
38,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22515814,29078ba5389b87488041ecea07fec29ed10c73b6a94bb0...,1,cruor,20699114,cruor,None,17294,user/1f36aaa0,v._.v._.v,None,None,None,cruor,cruor,user:17294
39,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22503493,ec11d706fd3f715318c2c64ee0f194342c032b95ea7dcf...,2,Greenstach,20688393,Greenstach,None,360588,user/bae424bd,greenstach,Greenstach_SSBM,Greenstach,None,greenstach,greenstach,user:360588
40,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22503492,2543a77796446507a0c34f9122fee9857e0bc51a8b311c...,0,Green Tea,20688392,Green Tea,,1877160,user/b9ed28c3,bostonredfox.,None,None,None,greentea,greentea,user:1877160
41,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22503332,9894f9ae093714f468e22e2c9fd473daa8bc91403ea336...,1,Duhaime,20688270,Duhaime,,1658344,user/1687b6d5,Duhaime#5974,jacobduhaime13,None,None,duhaime,duhaime,user:1658344
42,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22502986,f646c33953797d0a8575ea6f988aff82745ab68a10087b...,1,Vexoskeleton,20687943,Vexoskeleton,,12545,user/89ee8c25,ssj1,vexoskeleton,Vexoskeleton,None,vexoskeleton,vexoskeleton,user:12545
43,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22502973,87587d6cdcf31c3c346f1dc19b3236988f8e5d37daee22...,2,bonfire10,20687932,bonfire10,,409,user/3352d0d8,bonfire10,bonfireten,bonfire10,None,bonfire10,bonfire10,user:409
44,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22502971,ee0b2cb7cf208d66aadf672a4f754931b9679c6ecccdae...,2,Mojos Music | Love Chaac,20687928,Love Chaac,Mojos Music,3097137,user/dc8bd9ba,lovechaac,None,None,None,lovechaac,lovechaac,user:3097137
45,tournament/allston-allstars-vi-1/event/melee-s...,Melee Singles,22502444,df11d632826005ffd339f795ddf4e9786a10a91f4cf2b7...,1,MOOP,20687495,MOOP,,39824,user/0d9573f9,moop35,moop35,None,None,moop,moop,user:39824